### ISSUE TITLE
定时任务 task，mq consumer这类类似web controller这样的入口应该在什么模块里？

### ISSUE THREAD

**Issue by javaboy863** [alibaba/COLA#101]
似乎没找到对定时任务调度task这类入口的约束

**Comment by xiaozhiliaoo** [comment]
个人感觉 基础设施都应该在core里面，可以叫infrastructure或者framework， 业务具体的应该在service里面，定时任务和业务相关应该在service里面，但是mq consumer这种基础设施应该做到core里面，而业务层使用mq时候应该在service里面，

**Comment by significantfrank** [comment]
定时任务，mq处理的入口都可以放在app里面
