### ISSUE TITLE
示例项目“craftsman”缺少场景带入感

### ISSUE THREAD

**Issue by Ray-St** [alibaba/COLA#102]
hi,craftsman是一个基于cola框架的应用示例项目，主要是围绕 ATA的用户画像，做增删改查操作，但基于骨架代码，很难领会到cola的应用场景，建议给出更丰富的应用场景哈

**Comment by xiaozhiliaoo** [comment]
我理解cola框架是没有具体应用场景的，换句话它适用于任何业务场景，它是一种工程规范的指导，结合了ddd，ood，core domain，event这些概念，然后告诉你业务代码每一层该如何写，该如何思考系统边界上下文。

**Comment by spyvip** [comment]
+1

**Comment by significantfrank** [comment]
xiaozhiliaoo 说的对，cola是应用架构思想
