### ISSUE TITLE
groupId 怎么这么乱啊

### ISSUE THREAD

**Issue by zheyangnayang** [alibaba/COLA#107]
cola-framework-archetype-web 的 groupId 是com.alibaba.cola
cola-common 的却是 com.aliyun
但是代码里都是 import com.alibaba.cola.dto.Response; 之类的。
一个字，混乱。
而且用cola-framework-archetype-web 生成的代码也是错误百出。很多包名都要改过。

**Comment by xiaozhiliaoo** [comment]
我也感觉是啊，这项目下载下来导入idea很麻烦，看来只能借鉴下思想了

**Comment by significantfrank** [comment]
现在groupId统一改成了com.aliyun
