### ISSUE TITLE
组件图的关系是不是画的不对啊

### ISSUE THREAD

**Issue by zhaoqiuyang** [alibaba/COLA#113]
<img width="998" alt="0228E656-541F-4CD5-8032-26DCF73BF92D" src="https://user-images.githubusercontent.com/12506205/92083487-b2766f80-edf8-11ea-83eb-4240398f7653.png">
domain不是依赖client吧，是app依赖client

**Comment by shiinoMafuyu** [comment]
版本1.0 2.0 3.0在变，而且感觉现在生成的代码好像很多吗命名上的东西没改过来。涉及作者以前示例用的领域代码较多，作者认为的最重要的扩展点功能的使用实例没有。

**Comment by shiinoMafuyu** [comment]
就我看到的3.0而言 这个图是 controller--client--app--domain--infrastructure还有 app--infrastructure

**Comment by significantfrank** [comment]
你说的对，已修改
