### ISSUE TITLE
像领域事件EventHandler相关的在3.1.0删除报错

### ISSUE THREAD

**Issue by xfyang1988** [alibaba/COLA#123]
像领域事件EventHandler相关的在3.1.0删除报错？在升级cola的时候发现类似EventHandler都已经删除，
建议能否提供一个专门的jar处理相关的事件，否则以后项目升级cola的就无法升级向下兼容了

**Comment by xfyang1988** [comment]
已购买：代码精进之路：从码农到工匠，看看作者是怎么做到工匠精神的

**Comment by significantfrank** [comment]
不好意思，没有做向前兼容
