### ISSUE TITLE
fastjson 序列化时将BizScenario设为默认

### ISSUE THREAD

**Issue by AHBICJ** [alibaba/COLA#127]
in BizScenario.java
    public String getIdentityWithDefaultUseCase(){
        this.scenario = DEFAULT_SCENARIO;
        this.useCase = DEFAULT_USE_CASE;
        return getUniqueIdentity();
    }

**Comment by geyingqi777** [comment]
不止有这一种风险
我提了一个pull request, 列举了2个case
https://github.com/alibaba/COLA/pull/126#issue-519113616

**Comment by significantfrank** [comment]
Pull request accepted
