### ISSUE TITLE
当从状态机内部触发事件，没有好的办法，搞不好会循环引用

### ISSUE THREAD

**Issue by yizhixiaotaozi** [alibaba/COLA#128]
状态机build的时候依赖一个action，可能是个spring托管的bean
actionA内部又触发一个事件切到下一个状态执行actionB，action可能autowired状态机
这种场景如何优雅的处理呢？
选项：
1.actionA 和 actionB代码合并，这样相当于隐藏了内部事件。
2.actionA内部调用actionB, 这样就将状态定义从builder的地方挪到里面了，可以破坏预定的状态流程
3.使用一些技巧，把循环依赖解决

**Comment by significantfrank** [comment]
没有很明白问题

**Comment by winglechen** [comment]
Action_A {

    stateX --> stateA;

    stateMachine = xxx;
    stateMachine.fire(); //
}

Action_B {
     stateA --> stateB
}

Action_A 和 Action_B 无关联

这样有问题？

**Comment by yizhixiaotaozi** [comment]
> Action_A {
> stateX --> stateA;
> stateMachine.fire(); //
> }
> 
> Action_B {
> stateA --> stateB
> }
> 
> Action_A 和 Action_B 无关联
> 
> 这样有问题？

@Bean
StateMachine(ActionA a,ActionB b){
   return builder.build(a,b)
}

@Component 
class ActionA{
   @Resource
   private StateMachine statemanchine;
  
  public void change(){
    statemanchine.fire(State.a, State.b)
  }
}

**Comment by yizhixiaotaozi** [comment]
> 很明白

就是用@Bean 注解来build状态机，然后返回的时候，会去spring拿Action。  Action本身也会注入状态机。 这个时候就循环依赖了

**Comment by cnbeiyu** [comment]
我也遇到了这个问题，看上去没有什么比较好的办法
