### ISSUE TITLE
打包不能使用，怎么部署？？？

### ISSUE THREAD

**Issue by xieende** [alibaba/COLA#131]
现在通过maven install 打的包出来，运行不起来，缺少main，start不能跑，求教

**Comment by oldratlee** [comment]
再试着 按现在的文档走一下： 
https://github.com/alibaba/COLA#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8cola
看看是不是 OK了？  @xieende 

--------------

如果还有问题，给一下你的

- 完整的执行过程
- 和 出错的信息

**Comment by gebitang** [comment]
楼主应该只的是针对现在的 craftman示例的问题。 

文档中的说明`demo-web`已经不存在了。

---

目前sample的craftman项目start运行不起来，缺少main函数是因为缺少`spring-boot-maven-plugin`插件，没这个插件也就无法执行 `mvn spring-boot:run` 任务了

参考[这里](https://www.baeldung.com/spring-boot-run-maven-vs-executable-jar )，添加插件，配置指定启动的main函数所在的类。然后可以执行`mvn spring-boot:run`

如果需要打包为可执行的jar包，在start模块下执行`mvn clean package spring-boot:repackage`
