### ISSUE TITLE
架构图疑问

### ISSUE THREAD

**Issue by AnRic** [alibaba/COLA#132]
示例代码中 domain 依赖 client，但 架构图中未体现？

而且

跟了一下示例中的 MetricsController -> addATAMetric 方法，层级调用 大概是  controller层   ->   app层   -> domian 层   -> **infra 层  ->  (event 触发)app 层**  -> domain层  -> infra 层。
 
但是 通过enent发布  又已注释，不太懂什么意思。且看到在 3.1 之后的版本中，又要移除掉  event，那这个流程又要怎么走？？？

最后，可能是个人太过于愚笨，看了几天 cola 了，越看越迷糊，不知道大佬什么时候可以提供一个完整可运行的 demo？

**Comment by significantfrank** [comment]
已经移除了，内部事件机制EventBus，最近会对COLA做一个比较大的重构，把架构和功能分离的更干净一点
