### ISSUE TITLE
ApplicationContextHelper  45行 异常没抛出

### ISSUE THREAD

**Issue by swiftloop** [alibaba/COLA#133]
如题

**Comment by oldratlee** [comment]
给一下极简、可运行复现问题的Demo ，比如 在Github建一个Demo Repo  @swiftloop 

方便跟进排查～

**Comment by swiftloop** [comment]
https://github.com/alibaba/COLA/blob/9d1aa686632493dc7b4d855517e87b64e569af0a/cola-framework-core/src/main/java/com/alibaba/cola/common/ApplicationContextHelper.java

**Comment by oldratlee** [comment]
> https://github.com/alibaba/COLA/blob/9d1aa686632493dc7b4d855517e87b64e569af0a/cola-framework-core/src/main/java/com/alibaba/cola/common/ApplicationContextHelper.java

收到～

**Comment by swiftloop** [comment]
了解！！！
