### ISSUE TITLE
关于4.0.0版本中的扩展类BizScenario.java放到cola-component-extension-starter包里面的疑问

### ISSUE THREAD

**Issue by qq240996777** [alibaba/COLA#139]
在4.0.0的版本前，BizScenario.java这个包是放到cola-component-dto里面，是Command.java类中的一个属性。

放到dto里面的好处是第二方库里面方便扩展。
现在放到扩展包里面后，二方库需要用到该类的时候得需要依赖cola-component-extension-starte包。

**Comment by significantfrank** [comment]
好的
