### ISSUE TITLE
关于BizScenario类的json序列化反序列化的问题

### ISSUE THREAD

**Issue by qq240996777** [alibaba/COLA#140]
`{"bizScenario":{"uniqueIdentity":"defaultBizId.sceneMsg.defaultScenario"}}`

由于BizScenario类里面没有get set 方法，但是有getUniqueIdentity()方法，可以生成上述的json的。
但是序列化后反向再序列化就会出现 useCase = defaultUseCase 了，产生了变化。

**Comment by significantfrank** [comment]
解决方案是什么？
