### ISSUE TITLE
编译问题1.缺少guava 2.lombok版本不够新

### ISSUE THREAD

**Issue by CarlXK** [alibaba/COLA#143]
刚下载下来maven编译报两个错误，不知道其他同学有没有这个错误
1. nexus-staging-maven-plugin缺少guava包
2. lombok版本不够新

解决：
1. 增加guava包
            <plugin>
                <groupId>org.sonatype.plugins</groupId>
                <artifactId>nexus-staging-maven-plugin</artifactId>
                <version>1.6.8</version>
                <extensions>true</extensions>
                <configuration>
                    <serverId>sonatype-nexus-staging</serverId>
                    <nexusUrl>https://oss.sonatype.org/</nexusUrl>
                    <autoReleaseAfterClose>true</autoReleaseAfterClose>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>com.google.guava</groupId>
                        <artifactId>guava</artifactId>
                        <version>21.0</version>
                        <scope>compile</scope>
                    </dependency>
                </dependencies>
            </plugin>
2. lombok替换到版本 <version>1.18.12</version>

**Comment by dgyingling** [comment]
我也遇到了

**Comment by significantfrank** [comment]
提一个PR吧

**Comment by CarlXK** [comment]
问题已经解决
