### ISSUE TITLE
JDK版本11执行mvn install 安装组件会出现问题

### ISSUE THREAD

**Issue by Aronlele** [alibaba/COLA#146]
![image](https://user-images.githubusercontent.com/7881859/102188586-73c07d00-3ef0-11eb-9697-66772a40608c.png)
错误信息如下：
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-cmpile) on project cola-component-extension-starter: Fatal error compiling: java.lang.ExceptionInInitalizerError: com.sun.tools.javac.code.TypeTags -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugns:maven-compiler-plugin:3.1:compile (default-compile) on project cola-component-extension-starter: atal error compiling
打印异常如下：
![image](https://user-images.githubusercontent.com/7881859/102188803-ba15dc00-3ef0-11eb-9612-fa37e3e6a1a4.png)
建议：
把编译环境描述下，或者升级编译版本

**Comment by cheneyjuu** [comment]
使用JDK1.8进行编译吧。我也是11编译出错。

**Comment by Aronlele** [comment]
> 使用JDK1.8进行编译吧。我也是11编译出错。

嗯。

**Comment by significantfrank** [comment]
嗯，那就用1.8吧，11没有向后兼容么
