### ISSUE TITLE
Can not find extension with ExtensionPoint

### ISSUE THREAD

**Issue by acenra** [alibaba/COLA#147]
问题：
配置扩展点后，执行时报错，"Can not find extension with ExtensionPoint:"

跟踪源码发现：
ExtensionBootstrap.java中加了注解@Component，spring先扫描到此类时就会加载这个bean，但并不会执行它的init方法，导致扩展点不被加载。
同时在ExtensionAutoConfiguration类中有配置ExtensionBootstrap的bean，并初注明initMethod = "init"，init方法中会加载扩展点。
解决：删除掉ExtensionBootstrap.java的类注解@Component后，重新编译后，问题解决！

**Comment by significantfrank** [comment]
好的，已经merge，thanks for fixing the bug
