### ISSUE TITLE
几点疑惑

### ISSUE THREAD

**Issue by xjianyu** [alibaba/COLA#149]
1、domain要不要依赖client，4.0的demo是依赖了，但是感觉没必要啊，domain应该不需要依赖其他
2、infra要不要依赖client，按照4.0的代码结构图，是没有依赖的，但是如果不依赖的话，一些app工程的query如果是一些动态查询，入参是qry，这个qry类infra是要使用的吧，如果不使用，那就得convert一下，是不是变复杂了，并且按照代码结构图所示，infra也没有依赖dto组件，也query的分页返回dto貌似也没法使用。
![image](https://user-images.githubusercontent.com/19404942/102704201-2ad34480-42b3-11eb-9565-a1db47186785.png)
3、如果要提供dubbo接口出去被其他外部域调用，这个client暴露的类是不是太多了，应该大部分client类是内部域使用的。
4、MQ消息接收是app处理的，如果是发送MQ消息呢，是app来发，还是domain？
5、一些公共的util放在哪里比较合适呢

**Comment by significantfrank** [comment]
是的，infra可以直接依赖client。更多讨论，加我微信吧 25216348

**Comment by ywzou** [comment]
同样的疑问
