### ISSUE TITLE
domain模块为何要依赖client模块？

### ISSUE THREAD

**Issue by aking222** [alibaba/COLA#159]
不符合COLA架构范式，内部模块不应该依赖外部模块。

domain模块依赖client模块：

https://github.com/alibaba/COLA/blob/44e1fd8b0e7b77d2a3cdfbdb585cf0c7be8123bd/cola-archetypes/cola-archetype-service/src/main/resources/archetype-resources/__rootArtifactId__-domain/pom.xml#L25-L29

**Comment by zyj-nanjing** [comment]
![截屏2021-01-11 上午10 20 27](https://user-images.githubusercontent.com/53209268/104142533-ff95ce00-53f6-11eb-8f01-34ffc022d9e0.png)

**Comment by zyj-nanjing** [comment]
- 
![2021-01-11 上午10 20 27](https://user-images.githubusercontent.com/53209268/104142573-22c07d80-53f7-11eb-9c65-70890356df6c.png)
具体参考：https://blog.csdn.net/significantfrank/article/details/100074716

**Comment by aking222** [comment]
楼上是COLA2.0的图，COLA4.0的依赖关系图如下：
![image](https://user-images.githubusercontent.com/1535002/105276409-48f6d200-5bdc-11eb-8162-4a37c1e300f6.png)

具体参考：https://blog.csdn.net/significantfrank/article/details/110934799

**Comment by significantfrank** [comment]
是的，最新的依赖没问题
