### ISSUE TITLE
通过archetype生成的测试代码无法直接运行

### ISSUE THREAD

**Issue by baixiaodong** [alibaba/COLA#16]
通过提供的文档，生成了 demo 代码，无法直接运行，因为从远程仓库找不到 cola-framework 相关依赖，只能先将 framework mvn install 安装到本地， 但是 test 模块无法安装，提示找不到 com.sun.tools:jar:1.8。 这个应该是 system 级别的，maven 中央仓库应该没有，有也是低版本的（我的 maven 配置有问题？）。
建议通过 archetype 生成的代码能够直接运行起来，减少些入门成本

**Comment by niexiaolong** [comment]
archetype是cola-framework的一个demo，所以需要先安装代码中的cola-framework。
JDK是1.8的

**Comment by smalldok** [comment]
> 通过提供的文档，生成了 demo 代码，无法直接运行，因为从远程仓库找不到 cola-framework 相关依赖，只能先将 framework mvn install 安装到本地， 但是 test 模块无法安装，提示找不到 com.sun.tools:jar:1.8。 这个应该是 system 级别的，maven 中央仓库应该没有，有也是低版本的（我的 maven 配置有问题？）。
> 建议通过 archetype 生成的代码能够直接运行起来，减少些入门成本

提供的cola-framework工程里cola-test的版本是1.0.1所以会出现你这个问题，改成1.0.0即可；
哎，开源出来的东西一点都不用心，别人怎么放心用？
```
<artifactId>cola-test</artifactId>
<version>1.0.0-SNAPSHOT</version>
<name>cola-test</name>
```

**Comment by significantfrank** [comment]
已经升级到2.0.0，thanks
