### ISSUE TITLE
Domain中的模型定义与Infrastructure中的DO中的定义基本都是重复的？

### ISSUE THREAD

**Issue by krisjin** [alibaba/COLA#165]
Domain中的模型定义与Infrastructure中的DO中的定义基本都是重复的？
在infrastructure中单独配置了转换器，
这样每个模块各自维护了一套定义，是否会出现冗余的情况
是否可以直接在infrastructure中依赖domain中的模型定义

是否可以给解答下这个疑问，感谢！！

**Comment by xiaogangfan** [comment]
我尝试回答一下这个问题，domain中的模型是表达业务逻辑的，基础设施层中的模型是用来存储的，作用是不用的。

**Comment by xiaogangfan** [comment]
> Domain中的模型定义与Infrastructure中的DO中的定义基本都是重复的？
> 在infrastructure中单独配置了转换器，
> 这样每个模块各自维护了一套定义，是否会出现冗余的情况
> 是否可以直接在infrastructure中依赖domain中的模型定义
> 
> 是否可以给解答下这个疑问，感谢！！

我尝试回答一下这个问题，domain中的模型是表达业务逻辑的，基础设施层中的模型是用来存储的，作用是不用的。
而你以为的重复，是恰好模型的字段重复了，如果不重复的时候，就没法依赖了。同时也会造成耦合问题

**Comment by krisjin** [comment]
> > Domain中的模型定义与Infrastructure中的DO中的定义基本都是重复的？
> > 在infrastructure中单独配置了转换器，
> > 这样每个模块各自维护了一套定义，是否会出现冗余的情况
> > 是否可以直接在infrastructure中依赖domain中的模型定义
> > 是否可以给解答下这个疑问，感谢！！
> 
> 我尝试回答一下这个问题，domain中的模型是表达业务逻辑的，基础设施层中的模型是用来存储的，作用是不用的。
> 而你以为的重复，是恰好模型的字段重复了，如果不重复的时候，就没法依赖了。同时也会造成耦合问题

应该也不是恰好重复了，数据对象和模型对象基本都是映射的关系，从分层的结构来说，他们是属于不同层的领域，应该定义不同层的对象类来实现各自的需求，面对这样的冗余，都提供了各自的转换类。

在以前的开发中都是以核心的业务领域对象为基础模型，基础设施层依赖domain中的对象定义，不在重新定义 DataObject。

从分层结构划分角来看，确实存在耦合的问题，但是好像也存在弊端，那就是，多了很多的冗余的类，这些类很多都相似。

一直面对这样的问题，很是纠结。

让我的思绪在飞一会吧........
