### ISSUE TITLE
根据id查询的接口，有没有必要写qry和qryexe？

### ISSUE THREAD

**Issue by modefang** [alibaba/COLA#168]
下面这样是不是也可以

接口
/users/{id}

// adapter UserController
    @GetMapping(value = "/users/{id}")
    public SingleResponse<UserDTO> user(@PathVariable long id) {
        return this.userService.getById(id);
    }

// app UserServiceImpl
    @Resource
    private UserRepository userRepository;

    public SingleResponse<UserDTO> getById(long id) {
        Optional<UserDO> optional = this.userRepository.getById(id);
        UserDTO userDTO = null;
        if (optional.isPresent()) {
            userDTO  = new UserDTO();
            BeanUtils.copyProperties(optional.get(), userDTO);
        }
        return SingleResponse.of(userDTO);
    }

**Comment by sanyuedev** [comment]
同样有这样的疑问

删除也是传 id

**Comment by significantfrank** [comment]
it depends，如果很简单简洁，可以不写
