### ISSUE TITLE
wap、wireless、mobile、web这分别代表啥

### ISSUE THREAD

**Issue by alive-z** [alibaba/COLA#169]
https://blog.csdn.net/significantfrank/article/details/110934799
此博客中提到了wap、wireless、web

生成的代码中
提到了mobile、wap、web

两边没对应上，有点蒙圈

然后我的理解，不知道是博客中还是代码中有一边是不正确的（看起来像博客中）

然后就是，在Adapter层中，分为了Adapter和Controller
可否理解为，Controller是公用的，而Adapter是针对其他两端做的各自两端的事情？

**Comment by significantfrank** [comment]
wap是无线网页，mobile和wireless是原生的无线，web是电脑浏览器。Adapter（以前叫controller）是对这三端的适配
