### ISSUE TITLE
将方法封装成CmdExe类有什么好处？

### ISSUE THREAD

**Issue by Michael1024-CJX** [alibaba/COLA#170]
第一次见这种写法，这样不是会造成类太多吗？

**Comment by krisjin** [comment]
应该是命令模式的一种应用，这样操作，确实会导致类的变多，但是也会带来好处，那就是业务层的隔离。

不知回答的是否合适，欢迎讨论。

**Comment by JPCui** [comment]
建议先熟悉一下 CQRS

**Comment by Michael1024-CJX** [comment]
@JPCui 感谢指点，了解一下CQRS，将Command与Query进行服务分离，但看起来在COLA的demo中，是将这两种服务部署在一个应用中的不同接口上。

**Comment by significantfrank** [comment]
主要是让service作为facade的自责变得单一，让业务逻辑在exe里面执行
