### ISSUE TITLE
关于clientobject的类跟dataobject类属性是一样的？

### ISSUE THREAD

**Issue by geekrusice** [alibaba/COLA#173]
最近刚刚使用COLA框架，DEMO中的例子是clientobject的类跟dataobject类属性是一样，我按照这种思想去写的时候，一个实体类会被copy到两个地方，发生改变的时候，CO也需要跟着改变（当字段确实需要更新/新增/查询时）。请问是我用CO的思想不正确吗？

**Comment by lslvxy** [comment]
一般是一样的
某些场景是不一样的,
举个例子
User 关联 Role
DO中设计是User中包含一个roleId字段
CO则是用对象关联,或者CO中加上 roleId,roleName这些

**Comment by significantfrank** [comment]
楼上正解
