### ISSUE TITLE
Condition的设计目的是啥？没看出这里面的必要性

### ISSUE THREAD

**Issue by acpipe** [alibaba/COLA#174]
经典状态机的元素就四个：

- start status
- end status
- event
- action
为什么引入一个condition，是为了解决特定领域的问题吗？

博客上解释：表示是否允许到达某个状态。不允许到达某个状态，那么就不会触发这个事件呀？不理解这个设计。

**Comment by significantfrank** [comment]
if(condition) do action，是用来判断status是否可以流转的
