### ISSUE TITLE
COLA扩展点注册机制与Spring AOP代理类不兼容问题

### ISSUE THREAD

**Issue by euclideanrn** [alibaba/COLA#175]
当扩展点被Spring AOP代理时，COLA启动过程中找不到 `@Extension`注解、扩展点对应的接口。

**Comment by euclideanrn** [comment]
当扩展点的实例同时也被 Cglib 代理时，会导致 COLA 扩展点初始化报NPE。
![image](https://user-images.githubusercontent.com/13493334/107080199-e896a000-682b-11eb-8a7a-1cba87ffdda4.png)

**Comment by significantfrank** [comment]
是的，已经enhance修复
