### ISSUE TITLE
domainservice这个包下面应该是放领域服务吗？那服务对应的实现应该放在哪里？

### ISSUE THREAD

**Issue by cy503328434** [alibaba/COLA#180]
根据4.0的博客中写道，领域能力推荐使用包：ability，这个包下包括领域能力和DomainService。但是我点比较困惑，一般领域服务可能是以接口的形式存在，如果我拉包名叫ability或者domainservice的话，那我服务服务接口的实现应该放在哪里比较合适，是在ability再建一个子包，叫ability.impl吗？

**Comment by Vietthang91** [comment]
.

**Comment by significantfrank** [comment]
是的，如果是接口的话，需要impl包做区分
