### ISSUE TITLE
infrastructure直接引入domain层的gateway会不会太笨重了？

### ISSUE THREAD

**Issue by Shiyajian** [alibaba/COLA#182]
infrastructure和domain层调用是通过gateway的，这个gateway可以是infrastructure提供，或者domain层定义，目前是domain层定义，这个也可以接受。 但是infrastructure直接在maven依赖中应用整个domain层，是不是太笨重？是不是考虑把gateway单独抽取个接口包供infrastructure层使用，就像client模块一样

**Comment by charliewong001** [comment]
我理解gateway必须domain层定义，因为gateway设计的意义在于解耦infrastructure的实现。举个例子，如果infrastructure层的实现由mysql变更为H2，则只需要变更infrastructure就可以了。如果infrastructure定义，那下层有变化，domain核心层也会被动变化，这样就背离了设计的初衷。

**Comment by fuxiaome** [comment]
> 我理解gateway必须domain层定义，因为gateway设计的意义在于解耦infrastructure的实现。举个例子，如果infrastructure层的实现由mysql变更为H2，则只需要变更infrastructure就可以了。如果infrastructure定义，那下层有变化，domain核心层也会被动变化，这样就背离了设计的初衷。

楼主的意思并不是说gateway的定义放在infrastructure层中，而是说将gateway的定义信息单独抽离为一个模块出来，然后domain层和infrastructure层都去依赖这个模块的包是不是更好一点。这样的话可以解决infrastructure层直接依赖domain层时也会感知到一些自己并不关注的领域服务的定义和实现的问题，更加契合最少知道原则。也希望@Frank可以解答下现在这样设计的背后考量

**Comment by significantfrank** [comment]
也是可以的，的确有一些团队是把gateway独立出来作为一个层次使用的

**Comment by gaochengyidlmu** [comment]
> 

gateway 的返回值是entity，也就意味着gateway需要依赖domain，所以没啥区别
