### ISSUE TITLE
Client 层的 API 定义 和 Controller 层的进一步抽象

### ISSUE THREAD

**Issue by RainPoetry** [alibaba/COLA#183]
个人有一个不成熟的想法，不知道可不可行，首先，我们把所有的请求都抽象成是一个操作指令，能不能把 Client 层定义 API 那块以及整个 Controller 层用一个 Dispatcher 代替掉，用户只需要定义DTO对象（包含请求数据类型、URL 、GET/POST 等内容），Dispatcher 自动将 DTO数据 路由给对应的 APP 层去处理并接受处理结果和返回

**Comment by RainPoetry** [comment]
更准确一点是将 DTO + Controller 层 转换为 带有 Controller 层能力的 DTO 对象

**Comment by significantfrank** [comment]
Client还有一个作用是作为RPC的SDK，所以需要单独成为一个module
