### ISSUE TITLE
使用COLA架构因为业务需求导致循环依赖

### ISSUE THREAD

**Issue by aliangooo** [alibaba/COLA#184]
![image](https://user-images.githubusercontent.com/44746149/109584003-c991e200-7b3b-11eb-9894-561a69164cbc.png)
![image](https://user-images.githubusercontent.com/44746149/109584085-ea5a3780-7b3b-11eb-8c52-cb7f0b2f3371.png)
如图，因为两个模块之间有调用关联，可是在编译的时候会导致循环依赖，这个是类放置的有问题吗，可是看一些开源项目也是这样子写的，

**Comment by kissss** [comment]
我们的gateway 层不是放到 domain这里的，是放到 infr里面

**Comment by significantfrank** [comment]
gateway是在domain里面，domain不能对infra有依赖，gateway的返回值是domain entity不是do
