### ISSUE TITLE
有时间能更新下samples吗？

### ISSUE THREAD

**Issue by Ryoui** [alibaba/COLA#186]
第一次接触，还是有点懵的？samples和文档描述结构不一致

**Comment by AnRic** [comment]
同求，关注很久了，但例子总感觉和博客描述不一致，希望有个新版的示例，帮助理解

**Comment by hyhdfz** [comment]
+1

**Comment by FastLu17** [comment]
+1

**Comment by Ryoui** [comment]
脚手架那更新太慢了，现在还停留在3.0.0，能不能花点时间更新下.......

**Comment by Ryoui** [comment]
com.alibaba.cola.catchlog.CatchLogAspect使用了lombok@Slf4j,可不可以不用？

**Comment by significantfrank** [comment]
有时间，我出一个新的demo
