### ISSUE TITLE
骨架工程里面没有扩展点案例，没有多业务线扩展能力案例，没有起到指导作用，应添加上？

### ISSUE THREAD

**Issue by cholf** [alibaba/COLA#188]
骨架工程里面
1.没有扩展点案例
2.没有多业务线扩展能力案例
3.没有领域服务（能复用的case）案例
都应加上，别文章说的漂亮，没有落地基本案例嘛，不然怎么指导？

**Comment by bruce121381** [comment]
是啊是啊，找半天没找到扩展点的demo，对于一个完全不知道的这个人来说很难入手啊...

**Comment by FastLu17** [comment]
在cola-component-extension-starter源码的test里面有demo额
