### ISSUE TITLE
infrastructure层可以依赖client层吗？

### ISSUE THREAD

**Issue by justable** [alibaba/COLA#189]
我看4.0的博客中client层只被app层依赖。

**Comment by kissss** [comment]
为啥要依赖 client层

**Comment by justable** [comment]
@kissss 多参数查询场景中，我用client层的Qry来接查询参数，然后在app层直接把这Qry传给infrastructure层的DAO了，造成了依赖。正确应该怎么做？

另外阿里云初始化的代码（博客说云生成器不是最新版本）中infrastructure层也直接使用了client层的CO。

**Comment by significantfrank** [comment]
可以依赖
