### ISSUE TITLE
craftsman smaples和阿里云脚手架、本地maven命令生成包结构不一致

### ISSUE THREAD

**Issue by VanPersies** [alibaba/COLA#196]
老师，看你CSDN文章https://blog.csdn.net/significantfrank/article/details/110934799?spm=1001.2014.3001.5501，代码包结构在领域做一个顶层划分，然后在领域内，再按照功能进行分包。
但实际craftsman中domain和Infrastructure 工程师先按功能再按领域；阿里云的脚手架也有同样问题。

至于通过本地maven命令生成的代码中Infrastructure工程按领域分包了，但里面没有按照功能分包。

生成的service工程里面domain依赖client包，这个是不是不对啊？

老师能不能给一个比较好的工程模板？
@oldratlee @wzslw @jutem @meishenme

**Comment by significantfrank** [comment]
阿里云的有些滞后，正确的做法是先按照领域分

**Comment by oldratlee** [comment]
相关的Issue及其解答：

> - https://github.com/alibaba/COLA/issues/378#issuecomment-1408134662
>   > 应该是不支持了，直接用Archetype生成也很方便 by **`COLA` author** @significantfrank
> - https://github.com/alibaba/COLA/issues/354#issuecomment-1303032197
>   > 阿里云那个过时了，直接用archetype生成 by **`COLA` author** @significantfrank
> - https://github.com/alibaba/COLA/issues/196#issuecomment-872061727
>   > 阿里云的有些滞后，正确的做法是先按照领域分 by **`COLA` author** @significantfrank
> - https://github.com/alibaba/COLA/issues/283#issuecomment-1110817558
>   > 找阿里云的同学更新吧  by **`COLA` author** @significantfrank
