### ISSUE TITLE
能否出一个使用文档？

### ISSUE THREAD

**Issue by DDDInJava** [alibaba/COLA#198]
1. start.aliyun.com/boostrap.html生成的太乱了。还不如直接mvn命令生成 。
2. 生成的代码里面好多都是错误的路径。而且部分类都不知道干嘛的，注释也没有
3. @CatchAndLog 这种注解意思不明确，缓存并打印日志？源码连注释都没有
4. client下有个事件包，这里的事件作用是什么？比如我添加了一个消费者，然后通过mq之类的发送短信通知？

**Comment by significantfrank** [comment]
都是内部项目 不好开源
