### ISSUE TITLE
sample不是COLA4.0的

### ISSUE THREAD

**Issue by smilucky** [alibaba/COLA#199]
sample内容比较丰富了，很有参考价值。但是好像不是COLA4.0应用框架下的，能出一个COLA4.0的sample吗？

**Comment by significantfrank** [comment]
<cola.framework.version>4.1.0-SNAPSHOT</cola.framework.version>  是4.0的啊

**Comment by liuzhaowei55** [comment]
> <cola.framework.version>4.1.0-SNAPSHOT</cola.framework.version> 是4.0的啊

4.1.0-SNAPSHOT 加载不到
