### ISSUE TITLE
cache-log-starter 日志问题

### ISSUE THREAD

**Issue by wangkang09** [alibaba/COLA#201]
![image](https://user-images.githubusercontent.com/41175635/120161313-bde0b500-c229-11eb-828b-b42bde1f9bcd.png)
这个 error 是不是写错了，是不是 isErrorEnabled？

**Comment by significantfrank** [comment]
log.warn("BIZ EXCEPTION : " + e.getMessage());
            //在Debug的时候，对于BizException也打印堆栈
            if(log.isDebugEnabled()){
                log.error(e.getMessage(), e);
            }
