### ISSUE TITLE
根据COLA4的sample代码，对层次划分的个人理解

### ISSUE THREAD

**Issue by JunTaoYuan80** [alibaba/COLA#203]
个人理解，欢迎大家拍砖~

##层级说明
### 1.controller层
----
负责对前端展示（web ，wireless ，wap ）的路由和适配

### 2.app层
----
对CRUD功能的原子操作及组合操作的封装，依赖client层，实现client层的api接口，使client统一对外暴露crud功能及业务逻辑功能

### 3.client层
----
根据CQRS原则，进行封装dto,context等对象，并对外提供api的接口功能

### 4.domain层
----
整个COLA架构的核心层，对领域的定义、封装、逻辑处理，通过防腐层(gateway)对外提供能力，高内聚领域模型的变化。
领域是应用的核心，不依赖任何其他层次。
通过领域服务（Domain Service ）和领域对象（Domain Entity ）的方法对App 层提供业务实体和业务逻辑计算

### 5.infrastructure层
----
基础设施层，主要负责技术细节问题的处理，比如数据库的CRUD 、搜索引擎、文件系统、分布式服务的RPC、外部服务HTTP 等
此外，领域防腐的重任也落在这里，外部依赖需要通过gateway的转义处理，才能被上面的App 层和Domain 层使用

**Comment by JunTaoYuan80** [comment]
应用系统的公共常量值、枚举值、工具类utils 这些应该放到哪一层？？？

**Comment by significantfrank** [comment]
理解的正确，常量、枚举、工具类是什么地方用到放什么地方

**Comment by liufree** [comment]
> 理解的正确，常量、枚举、工具类是什么地方用到放什么地方
如果常量、枚举、工具类在多个层级都用到了，放在哪里合适

**Comment by sanyuedev** [comment]
> 个人理解，欢迎大家拍砖~
> 
> ##层级说明
> 
> ### 1.controller层
> 负责对前端展示（web ，wireless ，wap ）的路由和适配
> 
> ### 2.app层
> 对CRUD功能的原子操作及组合操作的封装，依赖client层，实现client层的api接口，使client统一对外暴露crud功能及业务逻辑功能
> 
> ### 3.client层
> 根据CQRS原则，进行封装dto,context等对象，并对外提供api的接口功能
> 
> ### 4.domain层
> 整个COLA架构的核心层，对领域的定义、封装、逻辑处理，通过防腐层(gateway)对外提供能力，高内聚领域模型的变化。
> 领域是应用的核心，不依赖任何其他层次。
> 通过领域服务（Domain Service ）和领域对象（Domain Entity ）的方法对App 层提供业务实体和业务逻辑计算
> 
> ### 5.infrastructure层
> 基础设施层，主要负责技术细节问题的处理，比如数据库的CRUD 、搜索引擎、文件系统、分布式服务的RPC、外部服务HTTP 等
> 此外，领域防腐的重任也落在这里，外部依赖需要通过gateway的转义处理，才能被上面的App 层和Domain 层使用

太牛了 我想请问一下 认证和授权该放哪里呢

**Comment by alansun2** [comment]
> 理解的正确，常量、枚举、工具类是什么地方用到放什么地方

Client 和 基础层都用到的枚举类应该放哪里？
