### ISSUE TITLE
[BUG] 项目中是cola-archetypes-parent,maven仓库是cola-archeytpes-parent不一致

### ISSUE THREAD

**Issue by Ryoui** [alibaba/COLA#208]
```
<!-- https://mvnrepository.com/artifact/com.alibaba.cola/cola-archeytpes-parent -->
<dependency>
    <groupId>com.alibaba.cola</groupId>
    <artifactId>cola-archeytpes-parent</artifactId>
    <version>4.0.1</version>
    <type>pom</type>
</dependency>
```
1,这是maven仓库的archeytpes，项目中是archetypes，写错了吧，一个是yt,一个ty，正确应该是archetypes吧。
2,clone到本地后install后，生成的版本号不对：
```
<groupId>com.alibaba.cola</groupId>
    <artifactId>cola-archetypes-parent</artifactId>
    <version>4.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>${project.artifactId}:${project.version}</name>
    <description>${project.artifactId}</description>
    <url>https://github.com/alibaba/COLA</url>
```
这里是4.1.0-SNAPSHOT，应该是4.0.1-SNAPSHOT吧
[https://gts-workorder.oss-cn-beijing.aliyuncs.com/20210618/17926e1c-edd3-4131-a77f-5a168fd71824/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20210618091040.png
](url)

**Comment by Ryoui** [comment]
https://gts-workorder.oss-cn-beijing.aliyuncs.com/20210618/17926e1c-edd3-4131-a77f-5a168fd71824/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20210618091040.png

**Comment by significantfrank** [comment]
是最新的吗？搜索了代码 没发现你说的情况

**Comment by Ryoui** [comment]
是安装后自动生成的项目中archetypes和阿里云仓库中archetypes不一致，是阿里云仓库里的archetypes错了
