### ISSUE TITLE
请教一下，是要生成很多个gateway 提供给不同的调用域吗？

### ISSUE THREAD

**Issue by loniecc** [alibaba/COLA#211]
比如
商品域，订单域，物流运输域。
订单域需要 商品的 名称，价格
物流运输域 需要商品的 名称，发货地

疑问
1. 是否需要两个gateway 来分别提供商品信息，还是一个gatway 内两种获取DTO的方法？
2. 对于不同的调用域，是否面向调用域输出DTO

**Comment by zhangucan** [comment]
> 

gatway输出的是实体和值对象，dto只在app层使用。

**Comment by zhangucan** [comment]
> > 
> 
> gatway输出的是实体和值对象，dto只在app层使用。

`商品域，订单域，物流运输域`之间的交互通过领域事件传输数据。

**Comment by significantfrank** [comment]
域（服务）之间的交互是通过DTO（或者event payload），这个API统一就好
