### ISSUE TITLE
为什么要用gateway去替换领域服务和仓储呢？

### ISSUE THREAD

**Issue by l308718280** [alibaba/COLA#213]
1. 背景
常规的DDD领域层，包含：领域对象、领域服务、仓储，领域对象的编排逻辑放在领域服务上，仓储用来作为领域对象的数据解耦层。

2. 我的问题
i. 通过gateway去替换了领域服务+仓储的概念，是否无法沉淀编排流程了？
ii. app层直接使用infrastructure里面的东西，产生的耦合性，导致无法解耦infrastructure层（无法保证修改Mapper接口而不修改app层）

以上两个问题的决策是出于什么样的理由呢？先提前感谢大佬们回答~

**Comment by zhangucan** [comment]
第二个问题我这边是这样理解的。领域服务+仓储通过gateway实现，app直接调用gateway可以接耦infrastructure 层。

第一个问题我也有同样的疑问，domain不调用infrastructure，那么领域实体的调用只能通过gateway去实现。
初衷是领域层防腐，现在强行去掉了领域服务的概念。这样是否合理？

**Comment by dujiecn** [comment]
仓储不属于领域层的一部分，ddd世界里只会把仓储当作存放或者创建对象的池子看待
对于第二个问题，我的理解是支持cqrs架构。所以app直接引用infra层

**Comment by hunao0221** [comment]
对于第一个问题同样不大理解。
这样看来，Cola用`Executor + Gateway`  替代了领域服务和仓储， 但是我不明白的做的目的，这样application层变厚了，而domain变薄了。
当然作者也说了，COLA也不是DDD，所以这还是能接受的。
> 你可能会有疑问，为什么Domain的model是可选的？因为COLA是应用架构，不是DDD架构。在工作中，很多同学问我领域模型要怎么设计，我的回答通常是：无有必要勿增实体。领域模型对设计能力要求很高，没把握用好，一个错误的抽象还不如不抽象，宁可不要用，也不要滥用，不要为了DDD而DDD。
————————————————
版权声明：本文为CSDN博主「张建飞（Frank）」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/significantfrank/article/details/110934799

**Comment by sundong1982** [comment]
Executor和domainservice是完全不同的两个东西，Executor是cqrs里面的command执行器，cqrs里r没有执行器这个东西，cola应该是想有个facade的概念在r里加入了。gateway不只是包含repository，概念更广 。 个人见解。

**Comment by significantfrank** [comment]
楼上正解，对于简单的业务场景，service+dao也挺好
