### ISSUE TITLE
请问sample什么时候可以更新一下

### ISSUE THREAD

**Issue by kun1988** [alibaba/COLA#214]
请问sample什么时候可以更新一下，谢谢

**Comment by Ryoui** [comment]
一个月前作者关issues时说的是，抽时间。看来比较忙

**Comment by hyhdfz** [comment]
什么时候更新?

**Comment by Ryoui** [comment]
一个4.0的例子
https://github.com/AmosWang0626/think-cola

**Comment by significantfrank** [comment]
最新的sample：https://github.com/alibaba/COLA/tree/master/samples/charge
