### ISSUE TITLE
Entity可以使用gateway吗 ？

### ISSUE THREAD

**Issue by zhangucan** [alibaba/COLA#216]
https://github.com/alibaba/COLA/blob/faecdfcb9e82e13144eef2334cf9cd6f44a2610b/cola-components/cola-component-domain-starter/src/test/java/com/alibaba/cola/domain/Customer.java#L20

**Comment by dujiecn** [comment]
可以的 ddd的概念。

**Comment by chifuqi** [comment]
基础设施层应该依赖DOMAIN层，而DOMAIN层不应该依赖基础设施层。所以我认为不应该使用gateway，请斧正

**Comment by leechor** [comment]
> 基础设施层应该依赖DOMAIN层，而DOMAIN层不应该依赖基础设施层。所以我认为不应该使用gateway，请斧正

4）基础实施层（Infrastructure Layer）：主要负责技术细节问题的处理，比如数据库的CRUD、搜索引擎、文件系统、分布式服务的RPC等。此外，领域防腐的重任也落在这里，外部依赖需要通过gateway的转义处理，才能被上面的App层和Domain层使用。
https://blog.csdn.net/significantfrank/article/details/110934799

**Comment by zhangucan** [comment]
最近在重构项目实践了一下，gateway的最好只在领域服务或者app层进行引用。

**Comment by significantfrank** [comment]
gateway本来就是用来解耦Domain和Infrastructure的，所以Domain中当然可以用
