### ISSUE TITLE
4.0.1版本中 dto模块没有ClientObject?

### ISSUE THREAD

**Issue by jhmarryme** [alibaba/COLA#217]
请问ClientObject这个类是被移除了吗
![image](https://user-images.githubusercontent.com/40780905/128129441-3811e8c3-79bc-4555-a37d-a3b9975903ba.png)
在craftsman中使用了这个类, 通过git最新版本的代码中能找到这个类, 但引用的4.0.1jar包中实际并没有
![image](https://user-images.githubusercontent.com/40780905/128130239-3bc5dbd4-76a9-467c-9e10-24922baadc3d.png)

**Comment by oldratlee** [comment]
发布了 `v4.1.0`：  @jhmarryme 
https://github.com/alibaba/COLA/releases/tag/COLA4.1.0
