### ISSUE TITLE
archetype创建项目生成的customer太糟糕了

### ISSUE THREAD

**Issue by hunao0221** [alibaba/COLA#222]
archetype创建项目是可不可以完善一下customer的demo，4.0.1生成的根本就是个半成品，很乱。

**Comment by significantfrank** [comment]
你期望achetype生成的代码是怎么样的

**Comment by maybeyj** [comment]
最简单的增删改查接口没有

**Comment by BugCui** [comment]
> 最简单的增删改查接口没有

不是又个增和查的接口么，感觉demo属实简单了点。
建议增加app层调用domain层相关代码，要不没法串联起来啊。
😂

**Comment by hunao0221** [comment]
> 你期望achetype生成的代码是怎么样的

- 要么包含一个能各个模块串起来的demo
- 要么就是一个干净的工程

仅为个人意见
