### ISSUE TITLE
几点个人看法：

### ISSUE THREAD

**Issue by tianzhonghai** [alibaba/COLA#224]
1、Demo过于简单，不具参考性；里面的类组织有些乱。
2、Gateway容易让人误解为SpringCloud ApiGateway
3、充血的领域模型还是没有体现出来，比如聚合根，EventSource。还是领域对象的事务，领域对象的数据填充与Performance。比如我只要一个字段，难道每次都要查一整个对象？

**Comment by wwyy456258** [comment]
附议1 3两个点

**Comment by chifuqi** [comment]
附议，看完IDDD后，再看DEMO仍然觉得一头雾水
另外， Mybatis如何集成到Repository没有看出来；另外阿里云创建的框架竟然运行不起来，也没有足够的说明，导致上手困难。

**Comment by VbiosWen** [comment]
> 1、Demo过于简单，不具参考性；里面的类组织有些乱。
> 2、Gateway容易让人误解为SpringCloud ApiGateway
> 3、充血的领域模型还是没有体现出来，比如聚合根，EventSource。还是领域对象的事务，领域对象的数据填充与Performance。比如我只要一个字段，难道每次都要查一整个对象？

感觉就是将一个大的 service 拆分成各个小的 exe，并没有体现 DDD 领域设计。

**Comment by Itdotaer** [comment]
同感，samples有点粗糙了。领域层的业务实践细节太少了

**Comment by SnailDev** [comment]
同感，samples有点粗糙了。领域层的业务实践细节太少了

**Comment by zhao-staff-officer** [comment]
主要是分层架构设计，组件功能根据项目选择用吧！！

**Comment by Degenerateman** [comment]
demo中app包下的service没看懂,是要体现防腐层还是啥?ATAMetricQryExe

**Comment by Degenerateman** [comment]
demo中app包下的service没看懂,是要体现防腐层还是啥?
ATAMetricQryExe跳过domain直接访问mapper,是不是和DDD冲突了

**Comment by zhangucan** [comment]
> 1、Demo过于简单，不具参考性；里面的类组织有些乱。 2、Gateway容易让人误解为SpringCloud ApiGateway 3、充血的领域模型还是没有体现出来，比如聚合根，EventSource。还是领域对象的事务，领域对象的数据填充与Performance。比如我只要一个字段，难道每次都要查一整个对象？

关于第三点，应该还是聚合设计太过臃肿。需要根据业务，设计小聚合。另外，把值对象用起来，每次持久化可以只保存值对象。

**Comment by zhangucan** [comment]
> 附议，看完IDDD后，再看DEMO仍然觉得一头雾水，主要是聚合对象特别是聚合对象存在集合的情况下，框架如何创建、更新？ 感谢

需要看业务设计。可以新增实体，在实体里记录聚合根的ID，也可以实现1对多。或者把` 聚合对象 ` 换成值对象引用，值对象的创建更新使用聚合根来操作。

**Comment by yhnnhyyhnn** [comment]
同感，看完DEMO后，没有感觉到DDD的优势在哪里。

**Comment by significantfrank** [comment]
COLA是应用架构，不是DDD架构哈，后续我会补充更多的sample进来

**Comment by Aoterr** [comment]
DDD 的充血模型 COLA 是没有体现出来吗？
