### ISSUE TITLE
app层向下看直接依赖 infrastrucure，而没有依赖 domain，给人感觉最重要的一层领域层被隐藏了

### ISSUE THREAD

**Issue by Hongpei-Chen** [alibaba/COLA#226]
1. app query操作直接调用 infrastrucure 里面数据库的Mapper接口是不是有点不合理呢，这好像起到隔离效果
2. 从 app层向下看直接依赖 infrastrucure，而没有依赖 domain ，是不是感觉很奇怪呢？给人感觉最重要的一层领域层被隐藏了

**Comment by Hongpei-Chen** [comment]
已有提问

**Comment by ruei0325** [comment]
domain意为核心业务，一般简单的get/find，Admin系统中table的简单搜索接口，没必要在domain中出现
