### ISSUE TITLE
CatchAndLog会让dubbo异常无法跨模块传递

### ISSUE THREAD

**Issue by sundong1982** [alibaba/COLA#227]
是否更推荐，不进行异常传递，代码统一处理业务异常。

为了兼容dubbo，BizException是否将继承RuntimeException改成继承Exception更合理。

**Comment by Raremaa** [comment]
这个问题我是这么考虑的，事实上，并不推荐使用异常来做流程控制，异常其实是昂贵的（当然不填充堆栈可能也还好），而且本身也是用来处理一些意外情况的。

- 如果是业务上的一些“异常”，其实应该包装成一个ResultSet结果集，而不是抛出一个异常，中断整个流程，最外面再统一捕获。
- COLA的cola-component-dto包中提供了多态的Response抽象，这其实就是一个结果集，任何业务“异常”都应该转化为Response而不是抛出一个语言级的Exception

**Comment by sundong1982** [comment]
感谢回复

**Comment by significantfrank** [comment]
> 

嗯，是这样设计考虑的，异常堆栈信息留在本地就好了
