### ISSUE TITLE
迫于没有讨论的地方，想问一下 Client 能依赖 Spring 吗 因为有个文件上传的逻辑

### ISSUE THREAD

**Issue by sanyuedev** [alibaba/COLA#229]

**Comment by nibaohua** [comment]
如果是采用Feign 或者 grpc之类的方式对外提供api， 如果不能有其他依赖的情况会比较尴尬

**Comment by oldratlee** [comment]
> 迫于没有讨论的地方，想问一下 Client 能依赖 Spring 吗 因为有个文件上传的逻辑

关于设计，

- 大家会给些看法
- 自己可以实践试试 :")
