### ISSUE TITLE
samples中event问题

### ISSUE THREAD

**Issue by Itdotaer** [alibaba/COLA#230]
**domainEventPublisher.publish(metricItemCreatedEvent);**
放在gatewayimpl中是不是不合适，这个impl已经和mybatis实现有关了（如果后续更换新的数据层实现类，那么推送逻辑也得新写）。

是不是DomainEventPublisher在领域层新建一个接口，然后在基础设施层实现接口，
具体推送在app层中调用，类似database的gateway实践更好？

**Comment by significantfrank** [comment]
发送领域事件也可以放在App里，唯一要注意的就是事务完整性，需要在领域实体持久化之后，再publish event
