### ISSUE TITLE
cola-component-catchlog-starter怎么隐藏错误信息

### ISSUE THREAD

**Issue by kun1988** [alibaba/COLA#231]
当我使用了组件cola-component-catchlog-starter之后，发生了一些runtimeException，我不想把异常的message封装到response的errMessage里面需要怎么处理呢？比如我不想把数据库的一些异常信息返回到客户端

**Comment by DrunkLiu** [comment]
目前版本不能隐藏，看了一下源码，除非重写他的方法，对标记了catchLog注解的方法做了切面，在发生异常的时候，catch到了异常，掉用ResponseHandler的handle方法，最终会打印日志
```
    private static Object handleColaResponse(Class returnType, String errCode, String errMsg) {
        try {
            Response response = (Response)returnType.newInstance();
            response.setSuccess(false);
            response.setErrCode(errCode);
            response.setErrMessage(errMsg);
            return response;
        }
        catch (Exception ex){
            log.error(ex.getMessage(), ex);
            return  null;
        }
    }
```

**Comment by wangchengcheer** [comment]
> 当我使用了组件cola-component-catchlog-starter之后，发生了一些runtimeException，我不想把异常的message封装到response的errMessage里面需要怎么处理呢？比如我不想把数据库的一些异常信息返回到客户端

找到处理办法没？我也遇到这个问题了。。。

**Comment by significantfrank** [comment]
加入了ResponseHandlerI扩展：https://github.com/alibaba/COLA/tree/master/cola-components/cola-component-catchlog-starter
