### ISSUE TITLE
app层可以直接依赖infrastructure能否理解为是一种折中

### ISSUE THREAD

**Issue by kongxinchi** [alibaba/COLA#244]
洋葱架构的infrastructure在最外层，我理解app要访问基础设施，也应该在app层定义接口，由infrastructure层实现，app理论上不应该直接依赖上infrastructure。

COLA的做法是否能理解为是一种折中，让COLA仍然保留按MVC方式写代码的可能，即使没有domain层，也可以继续按MVC的方式来写代码

[附：洋葱架构图](https://img2020.cnblogs.com/blog/1135193/202105/1135193-20210531121430499-290088953.png)

**Comment by significantfrank** [comment]
嗯 保留简单性，要不然很多简单的事情会被复杂化

**Comment by HollowLatte** [comment]
学习到了
