### ISSUE TITLE
使用阿里巴巴脚手架生成gradle版的COLA应用时，无法构建

### ISSUE THREAD

**Issue by zhengzhenning** [alibaba/COLA#247]
如图所示：
![image](https://user-images.githubusercontent.com/29723341/142432816-a4c05c5c-2f94-4850-b7cd-aca44b92b2d7.png)

使用 `gradlew build` 或 `gradle build` 构建应用时，报错

**Comment by significantfrank** [comment]
目前开源只支持maven
