### ISSUE TITLE
DataTunnelI这里面调用DB需要在内部注入mapper吗

### ISSUE THREAD

**Issue by hyz1994121** [alibaba/COLA#25]
在调用DataTunnelI获取数据这里, 是要在内部再来注入mapper来调用方法实现从DB获取数据吗, 还是可以直接用xml mapper实现对应的接口

**Comment by significantfrank** [comment]
Tunnel本身就是mapper，Tunnel的概念在2.0中已经去掉了，你也可以叫DAO

**Comment by hunshikan** [comment]
这一层是否要避免跨表操作呢？

**Comment by hunshikan** [comment]
> Tunnel本身就是mapper，Tunnel的概念在2.0中已经去掉了，你也可以叫DAO
这一层是否要避免跨表操作呢？
