### ISSUE TITLE
拉不下来当前4.1.0pom版本

### ISSUE THREAD

**Issue by fulln** [alibaba/COLA#252]
在用到状态机的时候发现COLA实现的状态机还挺方便易用,但是发现  单个from不能指向多个to,后来发现在4.1.0 版本有对应实现, 但是拉不下来4.1.0版本

**Comment by significantfrank** [comment]
你是说maven repo里的jar包吗？ 自己clone 源代码到本地build吧

**Comment by significantfrank** [comment]
你是说maven repo里的jar包吗？ 自己clone 源代码到公司build吧

**Comment by oldratlee** [comment]
@fulln released `v4.1.0`

https://github.com/alibaba/COLA/releases/tag/COLA4.1.0
