### ISSUE TITLE
关于@Entity的使用疑问

### ISSUE THREAD

**Issue by hiliushuo** [alibaba/COLA#26]
sample 中的domain包下面的  领域模型 为什么都没有用@Entity标识为一个bean呢？
想问一下：
领域模型到底应该被标识为一个bean吗？
      领域模型的行为可以依赖repository吗？
      领域模型的行为可以依赖外部的service吗？

**Comment by hiliushuo** [comment]
@significantfrank

**Comment by significantfrank** [comment]
可以依赖，但是不要直接依赖，要使用DIP
