### ISSUE TITLE
client层如何被调用方调用，如果使用的是springcloud的openfeign；这块如何修改

### ISSUE THREAD

**Issue by lzy-git** [alibaba/COLA#265]

**Comment by DrunkLiu** [comment]
这种client的设计就是dubbo这种RPC调用方式来的，openfeign是基于restful实现的，相当于RestTemplate调用了，所以，如果是feign调用，那么就取消client这层的service，只保留data包下的数据因型

**Comment by significantfrank** [comment]
楼上正解
