### ISSUE TITLE
想了解一下,为什么infra层包含domain层,而不是domain层包含infra层

### ISSUE THREAD

**Issue by KevinLiu2333** [alibaba/COLA#267]
为什么领域层在固件层内部...不是很明白

**Comment by DrunkLiu** [comment]
cola中的domain不是DDD中的domain，而是一个gateway，是调用其他领域的入口，而不会被其他领域调用。而想要被其他领域调用，需要通过app层提供的接口去调用，就是client

**Comment by Mosttaskiller** [comment]
隔离变化,domain 核心层其它层都可以引用,domain层不能引用别的层,技术实现和业务逻辑隔离,通过依赖倒置实现domain层调用基础设施层

**Comment by significantfrank** [comment]
楼上正解
