### ISSUE TITLE
COLA Framework中没有cola-extension模块

### ISSUE THREAD

**Issue by smalldok** [alibaba/COLA#27]
COLA Framework2.0 中没有cola-extension模块，而archetype中又指定依赖了cola-extension:jar:2.0.0

问题：
`[WARNING] The POM for com.alibaba.cola:cola-extension:jar:2.0.0 is missing, no dependency information available`

@significantfrank

**Comment by smalldok** [comment]
COLA Framework 的相关类，注释中还有`SOFA`的踪迹

**Comment by huang7230468** [comment]
同问

**Comment by puzzledcat** [comment]
还没修复啊

**Comment by significantfrank** [comment]
已经fix
