### ISSUE TITLE
cola状态机的condition会执行两次

### ISSUE THREAD

**Issue by win0909** [alibaba/COLA#274]
com.alibaba.cola.statemachine.impl.StateMachineImpl#routeTransition
![企业微信截图_16490685872668](https://user-images.githubusercontent.com/25101356/161527654-54fd2991-cd62-4251-920a-f4cabe0a9f97.png)

com.alibaba.cola.statemachine.impl.TransitionImpl#transit
![image](https://user-images.githubusercontent.com/25101356/161527721-ce15a594-71c4-466b-a379-a5ad9cc327b4.png)

单元测试结果
![企业微信截图_16490687345256](https://user-images.githubusercontent.com/25101356/161527741-bb17b102-6a46-41ee-b754-7334eea1dae7.png)

**Comment by win0909** [comment]
版本: 4.1.0

**Comment by significantfrank** [comment]
已经修复
