### ISSUE TITLE
请问下示例中的聚合根 UserProfile 直接引用了其他领域（metrics）里的值对象。是因为是示例程序所以这里简化了么？

### ISSUE THREAD

**Issue by oymy** [alibaba/COLA#275]
`@Data
@NoArgsConstructor
@Entity
@Slf4j
public class UserProfile {

    private String id;
    private String userId;
    private String userName;
    private String dep;
    private Role role;
    private String isManager;
    private Weight weight;
    private double totalScore;
    private double appQualityScore;
    private double techInfluenceScore;
    private double techContributionScore;
    private double devQualityScore;
    private double checkinCodeQuantity;

    private AppQualityMetric appQualityMetric;
    private InfluenceMetric influenceMetric;
    private ContributionMetric contributionMetric;
    private DevQualityMetric devQualityMetric;`

**Comment by significantfrank** [comment]
是的，淡化聚合根的概念，readable & workable 的 code更重要

**Comment by gracefullliam** [comment]
我想问一下metrics是啥意思，翻译软件好像不太准确。。。。
