### ISSUE TITLE
COLA2.0# cola-framework各module的version没改成2.0

### ISSUE THREAD

**Issue by smalldok** [alibaba/COLA#28]
```
<artifactId>cola-test</artifactId>  
<version>1.0.1-SNAPSHOT</version>  
<name>cola-test</name>  
```

<img width="517" alt="WeChat56eaed498c522c7248978a22fb70ae3f" src="https://user-images.githubusercontent.com/13725783/63701068-dce13480-c856-11e9-883c-7a91d5c0e566.png">

**Comment by significantfrank** [comment]
已经fix，thanks
