### ISSUE TITLE
如果对外暴露 RPC 服务（如：dubbo），是对 client 目录打包吗？

### ISSUE THREAD

**Issue by NOISEMOON** [alibaba/COLA#280]
demo 中的 client 里，只定义了 app 的接口。如果需要对外暴露 dubbo 服务该如何操作？
我能想到的分包方式是：把 dubbo 接口定义在 client 包中，把 dubbo impl 放在 adapter 包中。

但是这样又会导致 app 层依赖了 adapter 层的接口定义，另外还会把应用服务的定义（app api）暴露给外部服务，比较怪异。
难道是直接把 app 的 api 作为 dubbo 服务对外暴露？

**Comment by ahern88** [comment]
我跟你一样有同样的困惑，目前我的想法是client中定义接口和相关request和response的dto。
跟adapter同层定义了一个 xxx-dubbo 的模块作为client的实现，相关的业务编排还是在app层，不知道这样是否合理，总感觉还是有点奇怪。

**Comment by ahern88** [comment]
> 我跟你一样有同样的困惑，目前我的想法是client中定义接口和相关request和response的dto。
> 跟adapter同层定义了一个 xxx-dubbo 的模块作为client的实现，相关的业务编排还是在app层，不知道这样是否合理，总感觉还是有点奇怪。

我跟你一样有同样的困惑，目前我的想法是client中定义接口和相关request和response的dto。
跟adapter同层定义了一个 xxx-dubbo 的模块作为client的实现，相关的业务编排还是在app层，不知道这样是否合理，总感觉还是有点奇怪。

**Comment by NOISEMOON** [comment]
> 

是比较合理的解决方法~

**Comment by NOISEMOON** [comment]
> > 我跟你一样有同样的困惑，目前我的想法是client中定义接口和相关request和response的dto。
> > 跟adapter同层定义了一个 xxx-dubbo 的模块作为client的实现，相关的业务编排还是在app层，不知道这样是否合理，总感觉还是有点奇怪。
> 

是比较合理的解决方法~

**Comment by significantfrank** [comment]
client主要是作为consumer的SDK设计的，可以根据RPC框架调整
