### ISSUE TITLE
服务间循环依赖如何处理？

### ISSUE THREAD

**Issue by kdlan** [alibaba/COLA#282]
Domain 层引用 Gateway，Gateway 会封装对别的领域服务的调用。那如果别的服务的domain层，内部通过gateway调用了本服务的app层最终调用到domain 层，这个如何避免？

例如：

* 服务 A:  domain a -> gateway b rpc call ->app b 
* 服务 B:  app b -> domain b -> gateway a rpc call -> app a
* 服务 A: app a -> domain a 循环

**Comment by snifferhu** [comment]
可以再做一层业务聚合层服务C
由C来调用app a和app b来聚合服务
这样a与b就解开了相互间的依赖

**Comment by kdlan** [comment]
> 可以再做一层业务聚合层服务C 由C来调用app a和app b来聚合服务 这样a与b就解开了相互间的依赖

我也知道可以这么解，但是按cola的要求，这些都应该在domain里调用gateway吧，所以是想知道cola是怎么处理这个问题的

**Comment by pptech-dev** [comment]
> 可以再做一层业务聚合层服务C 由C来调用app a和app b来聚合服务 这样a与b就解开了相互间的依赖

我理解的是，domain是能存在聚合根的，不用单独弄一层聚合层

**Comment by pptech-dev** [comment]
> > 可以再做一层业务聚合层服务C 由C来调用app a和app b来聚合服务 这样a与b就解开了相互间的依赖
> 
> 我也知道可以这么解，但是按cola的要求，这些都应该在domain里调用gateway吧，所以是想知道cola是怎么处理这个问题的

我觉得不冲突，因为服务B对于你来说，他应该是一个黑盒子，他中间是否又有调回服务A其实你是不知道的。现在是你“假装”知道了这个事情 :)

**Comment by significantfrank** [comment]
相互依赖，是职责划分问题，可以考虑把相应职责归并到一个服务中去。
