### ISSUE TITLE
https://start.aliyun.com/bootstrap.html 是不是得更新了

### ISSUE THREAD

**Issue by hadesvip** [alibaba/COLA#283]
问题如标题。

**Comment by significantfrank** [comment]
找阿里云的同学更新吧

**Comment by oldratlee** [comment]
相关的Issue及其解答：

> - https://github.com/alibaba/COLA/issues/378#issuecomment-1408134662
>   > 应该是不支持了，直接用Archetype生成也很方便 by **`COLA` author** @significantfrank
> - https://github.com/alibaba/COLA/issues/354#issuecomment-1303032197
>   > 阿里云那个过时了，直接用archetype生成 by **`COLA` author** @significantfrank
> - https://github.com/alibaba/COLA/issues/196#issuecomment-872061727
>   > 阿里云的有些滞后，正确的做法是先按照领域分 by **`COLA` author** @significantfrank
> - https://github.com/alibaba/COLA/issues/283#issuecomment-1110817558
>   > 找阿里云的同学更新吧  by **`COLA` author** @significantfrank
