### ISSUE TITLE
您好，这个图示，调用组件实际中怎么是在app层内

### ISSUE THREAD

**Issue by xbyyz** [alibaba/COLA#286]
![image](https://user-images.githubusercontent.com/1674662/167307155-0527fce9-9ceb-4e9a-8471-78564a2dccd6.png)

**Comment by significantfrank** [comment]
没理解问题

**Comment by iYaDongWang** [comment]
app模块和domain模块直接依赖client模块，infr模块通过domain间接依赖client模块，adapter通过app间接依赖client模块，
因此所有的模块都可以使用组件
