### ISSUE TITLE
你好 从《代码精进之道》这边书过来的

### ISSUE THREAD

**Issue by helloweixun** [alibaba/COLA#288]
https://github.com/alibaba/COLA/tree/master/sample/craftsman 现在是404 请问是什么原因呢？

**Comment by huangdenghe** [comment]
sample 目录在 https://github.com/alibaba/COLA/commit/d2ebc550c937227c4fbd4b9ac73010fdad2b473a 这个 commit 中被重命名为 samples

现在的目录路径是 https://github.com/alibaba/COLA/tree/master/samples/craftsman
