### ISSUE TITLE
domain 的一些问题

### ISSUE THREAD

**Issue by Aoterr** [alibaba/COLA#289]
大佬你好，想问一下思路问题，望指教。

1. domain领域层，里面包含了 domain实体，gateway、ability，那么 app 层调用 domain领域层方法的时候，应该怎么调用，例如查询，创建是调用 gateway 接口，还是类似充血模型，在 实体中存在方法，并注入了gateway，来直接调用实体方法，亦或者在 alility 的 domainService 中实现，再调用。虽然示例中是直接调用 gateway，但是想问下，另外两种调用大佬是如何思考的？感觉充血模型更符合DDD
2. 基于问题 1 的基础上，如果一个 domain 实体是聚合的。那么是在 ability 里面进行聚合，还是在 Infrastructure 层聚合后返回
3. Infrastructure 层可否调用 domina 领域层的内容，原因是，某个领域的 gatewayimpl 可能依赖另一个领域的内容呢？

best wish，thankyou

**Comment by significantfrank** [comment]
1&2. 没有定式，主要看是否合适，判断依据：可读性、可理解性、简洁性，可维护性等。不要为了DDD而DDD
3. 可以
