### ISSUE TITLE
maven-archetype执行失败,The desired archetype does not exist (com:cola-framework-archetype-web:4)

### ISSUE THREAD

**Issue by 1092945539** [alibaba/COLA#294]
mvn创建应用失败
mvn archetype:generate -DgroupId=com.alibaba.cola.demo.web -DartifactId=demo-web -Dversion=1.0.0-SNAPSHOT -Dpackage=com.alibaba.demo -DarchetypeArtifactId=cola-framework-archetype-web -DarchetypeGroupId=com.alibaba.cola -DarchetypeVersion=4.0.1

Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.0.1:generate (default-cli) on project cola-archetypes-parent: The desired archetype does not exist (com:cola-framework-archetype-web:4)

mvn -v
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: D:\apache-maven-3.8.4
Java version: 1.8.0_202, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_202\jre
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

#https://github.com/alibaba/COLA/issues/187
maven镜像也已经替换

**Comment by significantfrank** [comment]
用4.1.0  https://search.maven.org/search?q=g:com.alibaba.cola
