### ISSUE TITLE
maven-archetype执行失败,The desired archetype does not exist (com:cola-framework-archetype-web:4)

### ISSUE THREAD

**Issue by 1092945539** [alibaba/COLA#295]
#294 
mvn archetype:generate -DgroupId=com.alibaba.cola.demo.web -DartifactId=demo-web -Dversion=1.0.0-SNAPSHOT -Dpackage=com.alibaba.demo -DarchetypeArtifactId=cola-framework-archetype-web -DarchetypeGroupId=com.alibaba.cola -DarchetypeVersion=4.1.0

archetypeVersion=4.1.0 各种版本都已尝试，都是一样提示The desired archetype does not exist (com:cola-framework-archetype-web:4)
没有明白为什么会寻找到com:cola-framework-archetype-web:4 ？

**Comment by returncode** [comment]
试了很久终有查出问题了，我的是因为Win10的终端问题造成的，终端好像把“.”后面的字符串给忽略了，mvn识别不了，就提示 (com:cola-framework-archetype-web:4)
解决方式是不要用Win10的终端里的 Windows PowerShell ，用 命令提示符，就不会出这个问题了。
![image](https://user-images.githubusercontent.com/2740548/184312621-5305ce3d-c0d6-4abb-b289-cbeb6337a3c9.png)
![image](https://user-images.githubusercontent.com/2740548/184312665-1999dcbf-38b6-468d-81fb-867622895c12.png)

**Comment by TDKSherlock** [comment]
牛逼，解决了！

**Comment by TDKSherlock** [comment]
> 试了很久终有查出问题了，我的是因为Win10的终端问题造成的，终端好像把“.”后面的字符串给忽略了，mvn识别不了，就提示 (com:cola-framework-archetype-web:4) 解决方式是不要用Win10的终端里的 Windows PowerShell ，用 命令提示符，就不会出这个问题了。 ![image](https://user-images.githubusercontent.com/2740548/184312621-5305ce3d-c0d6-4abb-b289-cbeb6337a3c9.png) ![image](https://user-images.githubusercontent.com/2740548/184312665-1999dcbf-38b6-468d-81fb-867622895c12.png)

感谢
