### ISSUE TITLE
状态机和spring的适配性

### ISSUE THREAD

**Issue by fulln** [alibaba/COLA#297]
我有使用到该状态机组件，然后使用的时候写了套针对状态机的使用的spring-start项目和相关注解，能不能为该项目提供个pr

**Comment by significantfrank** [comment]
发一个PR我看一下，合适的话，会accept

**Comment by GongZhengMe** [comment]
> 

请问状态机的初始化是否可以放在spring ioc中作为bean。这样使用会有问题吗
