### ISSUE TITLE
对的，代码已经修复：https://github.com/alibaba/COLA/pull/278/commits/0d69547363e312a97298acdf32cd4992ed7f09ed，版本没有发

### ISSUE THREAD

**Issue by chenyangshu** [alibaba/COLA#303]
对的，代码已经修复：https://github.com/alibaba/COLA/pull/278/commits/0d69547363e312a97298acdf32cd4992ed7f09ed，版本没有发

_Originally posted by @significantfrank in https://github.com/alibaba/COLA/issues/269#issuecomment-1182719397_

我的项目也遇到这个问题，急需有修复这个问题的正式版

**Comment by significantfrank** [comment]
最新修复版4.2.1 ：https://search.maven.org/artifact/com.alibaba.cola/cola-component-statemachine/4.2.1/jar
