### ISSUE TITLE
使用maven-archetype生成的代码的软件许可（License）问题

### ISSUE THREAD

**Issue by WillemJiang** [alibaba/COLA#329]
COLA 代码库是LGPL使用License， 但是没有标注 使用maven-archetype生成的代码的 License。
如果生成的代码还是按照 LGPL 进行许可，会给大家在企业内部使用这部分代码带来很多困扰。 
想问一下针对maven-archetype生成的代码会使用什么样的软件许可？

**Comment by oldratlee** [comment]
代码 与 其衍生代码 是不是应该没有关系，缺省自由的。

衍生代码工具 很常见，比如 大量maven archetype、注解工具 lombok、antlr。

**Comment by oldratlee** [comment]
这个 issue 先 close。如有进一步信息可以继续讨论。
