### ISSUE TITLE
COLA2.0# cola-framework中cola-test版本没有同步为2.0.0版本

### ISSUE THREAD

**Issue by QinZhanlong** [alibaba/COLA#33]
1）cola-test版本
源码中test中version为1.0.1
![image](https://user-images.githubusercontent.com/25076650/64070616-05be5b00-cc97-11e9-9964-ebac9ac88ea3.png)
替换成这样${cola.framework.version} ，则可以正常生成2.0.0test jar包

2）没有DomainEvent这个领域事件类
![image](https://user-images.githubusercontent.com/25076650/64070681-ecb6a980-cc98-11e9-9b88-201cecbabbad.png)

**Comment by significantfrank** [comment]
已经fix
