### ISSUE TITLE
请教@CatchAndLog为什么是提供service级别的logging和exception处理，@CatchAndLog作为Controller的切面不是更合理吗？

### ISSUE THREAD

**Issue by zhangyinghahaha** [alibaba/COLA#336]
请教@CatchAndLog为什么是提供service级别的logging和exception处理，@CatchAndLog作为Controller的切面不是更合理吗？

**Comment by flyingpassion** [comment]
@Pointcut("@within(CatchAndLog) && execution(public * *(..))")
    public void pointcut() {
    }
这个切面定义没限制在那一层是使用，Controller，service,任何一层跨bean调用都可以使用吧。
