### ISSUE TITLE
com:cola-framework-archetype-web:4

### ISSUE THREAD

**Issue by litaipo** [alibaba/COLA#337]
The desired archetype does not exist

**Comment by sly-APalmCat** [comment]
me  too.

**Comment by oldratlee** [comment]
@litaipo @sly-APalmCat 

please find available archetypes of `COLA`：

- https://central.sonatype.com/search?q=archetype&namespace=com.alibaba.cola
- ![image](https://user-images.githubusercontent.com/1063891/229847925-618a422f-ded7-41ab-bbe3-93b7f6eb87a7.png)

more infos please see the documentations of `COLA`.
