### ISSUE TITLE
如何集成mybatise-plus？

### ISSUE THREAD

**Issue by hnsongbiao** [alibaba/COLA#340]
如何集成mybatise-plus呢？client怎么写呢？client使用的是dto

**Comment by hnsongbiao** [comment]
哪位能提供一个集成mybatis-plus的demo?

**Comment by hnsongbiao** [comment]
搜遍了互联网没发现这个COLA框架与mybatisplus的集成方案

**Comment by zhangyingrepo** [comment]
自己集成mybatis-plus，gatewayimpl里面注入mapper就好了

**Comment by hnxiaoyuan** [comment]
你简单理解COLA只是一个模块分层的架子，，，实际你SpringBoot怎么集成Mybatis-Plus的，这里一样啊，没有区别啊
