### ISSUE TITLE
请问有没有计划将domainEvent收纳进COLA组件里？

### ISSUE THREAD

**Issue by xiwenzai** [alibaba/COLA#341]

**Comment by zhangyingrepo** [comment]
@xiwenzai 有对应实现吗？先参考一下

**Comment by xiwenzai** [comment]
> @xiwenzai 有对应实现吗？想参考一下

暂时还没有，可以在3.0.0版本里把common和core依赖里的event包的内容拷贝出来，自己打个包顶顶

**Comment by zhangyingrepo** [comment]
> > @xiwenzai 有对应实现吗？想参考一下
> 
> 暂时还没有，可以在3.0.0版本里把common和core依赖里的event包的内容拷贝出来，自己打个包顶顶

谢谢，看了看相关实现，感觉结合spring event自己来实现可能更加好用

**Comment by significantfrank** [comment]
嗯，Spring Event够用了
