### ISSUE TITLE
建议未来提供EventSouring的支持

### ISSUE THREAD

**Issue by GeTOUO** [alibaba/COLA#35]
因为没有框架的文档，大概看了一下代码。感觉 cmd和event的关系及在框架中的定位不是特别明确。本来我以为 cmd是由调用端(client)发起，cmd 转化为 领域事件，事件处理器消化更改状态，持久化并发出消息，消息响应调用端。但是不知道框架是不是这么设计的或者未来是否准备支持？因为如果要支持EventSouring的话，领域对象才能通过回放事件来恢复状态。只有事件被持久化。如果cmd处理器也涉及领域状态，就没有办法实现这个需求了。也不好控制回放和恢复。
cmd(client/consumer)->event(only domain model)->message(consumer/subscriber)

**Comment by significantfrank** [comment]
OK will consider it
