### ISSUE TITLE
坐标支持集合写法

### ISSUE THREAD

**Issue by heihei180** [alibaba/COLA#350]
现在坐标 是 精准坐标，即一个坐标只能匹配一个值，  是否可以支持匹配多个值呢？

![image](https://user-images.githubusercontent.com/38102241/192751833-d5c872e6-3dce-4578-818b-4c35b7b53665.png)

如果可以，我可以提供pr

**Comment by significantfrank** [comment]
可以，为了向前兼容，你新加一个Extensions annotation做多值匹配
