### ISSUE TITLE
aliyun cola bootstrap

### ISSUE THREAD

**Issue by lunasaw** [alibaba/COLA#354]
`git clone "https://start.aliyun.com/type=maven-project&language=java&architecture=cola&bootVersion=2.3.7.RELEASE&baseDir=cola-start&groupId=com.luna&artifactId=cola-start&name=cola-start&description=Demo%20project%20for%20Spring%20Boot&packageName=com.luna.cola-start&packaging=jar&javaVersion=1.8&dependencies=lombok,web,mysql,mybatis,validation,cola-core,cola-common,junit,commons-lang3,fastjson,arthas,h2&demos=mybatis/cola-start.git" cola-start`

![image](https://user-images.githubusercontent.com/52351139/194832270-18a2e311-b963-4dd1-a7bc-f92172418f02.png)

idea open Module 'src' not found

**Comment by lunasaw** [comment]
阿里云 bootstrap https://start.aliyun.com/bootstrap.html  生成的目录接口 带了 src 模块。

**Comment by significantfrank** [comment]
阿里云那个过时了，直接用archetype生成

**Comment by oldratlee** [comment]
已有的 Issue及其解答：

> - https://github.com/alibaba/COLA/issues/378#issuecomment-1408134662
>   > 应该是不支持了，直接用Archetype生成也很方便 by **`COLA` author** @significantfrank
> - https://github.com/alibaba/COLA/issues/354#issuecomment-1303032197
>   > 阿里云那个过时了，直接用archetype生成 by **`COLA` author** @significantfrank
> - https://github.com/alibaba/COLA/issues/196#issuecomment-872061727
>   > 阿里云的有些滞后，正确的做法是先按照领域分 by **`COLA` author** @significantfrank
> - https://github.com/alibaba/COLA/issues/283#issuecomment-1110817558
>   > 找阿里云的同学更新吧  by **`COLA` author** @significantfrank
