### ISSUE TITLE
EventBus相关问题？

### ISSUE THREAD

**Issue by 1154315454** [alibaba/COLA#355]
问题1：在实现领域事件时，为什么定义一个线程池去实现EventBus，而不是使用spring中的ApplicationEvent实现？
问题2：EventBus的主要目的是为了异步处理事件，此处为什么不直接使用spring的Async注解实现？

**Comment by wyyl1** [comment]
字面回答：这样可以不依赖 Spring

**Comment by 1154315454** [comment]
此处依赖于spring存在什么问题吗？

**Comment by wyyl1** [comment]
没有看具体代码，作为吃瓜群众过来聊个天

**Comment by significantfrank** [comment]
楼主说的也可以，这是为什么后面我们取消掉EventBus的原因
