### ISSUE TITLE
微服务中关于client实现问题的疑惑

### ISSUE THREAD

**Issue by tucke** [alibaba/COLA#356]
尝试在微服务中使用cola遇到点困惑，我们的服务暴露出去的client不仅仅是一个简单的 interface，我们还需要在其中加入 @FeignClient，以及@RequestMapping 等，以此减少其它微服务对当前微服务的对接工作。这样感觉 client 反而是需要在 adapter 层实现，因为application层暴露的只是一些service，而在微服务中是需要暴露HTTP接口出去，为了保证其它服务导入 client 依赖后能正常调用，当前微服务则需要确保服务能正常提供，所以需要在 Controller 中完整实现 client。这样就跟 cola 设计就存在一些差异

**Comment by wrxiang** [comment]
client中定义接口，入参返回值，@RequestMapping 等注解放在接口相应的方法上，接口的实现放在app层，虽然实现是controller，但我一般将他看做rpc服务的具体实现，通常我会将feign接口的具体实现命名为xxService

另一个问题是client中是否要引入spring-mvc注解相关的jar，既然client的职责是对外提供sdk，那么就需要根据服务采用的不同rpc方式做调整，而且引入的spring-mvc注解相关的jar作用域可以设置为provided，注解相关jar由消费方提供，避免消费方的依赖冲突
以上是我的理解

**Comment by wrxiang** [comment]
@significantfrank

**Comment by significantfrank** [comment]
补充一点，client的定位是sdk，和层次没有直接关系。如果我们的应用是纯后端微服务，实际上，是可以没有adapter层的。adapter是为了适配多端input，比如来自于pc，mobile，event的请求
