### ISSUE TITLE
infrastructure和domain依赖倒置带来的问题

### ISSUE THREAD

**Issue by suikelei** [alibaba/COLA#367]
依赖倒置的好处是解耦了。但是这样造成，如果domain想要依赖infrastructure的能力，infrastructure需要抽象出接口给domain用。
infrastructure里，数据访问层、远程调用都没有问题，可以抽象出接口。config也没问题，因为不需要被domain依赖；但是infrastructure所有的能力，并不是都能抽象出接口给domain用，比如：

1. common里，如果放工具类的话，就没有办法被 domain给用了。感觉只能把common独立出一个module来
2. 对于diamond、switch等配置类，按照六边形理论，他们上面的注解属于技术细节，不能直接被domain、app等依赖，貌似要放到infrastructure，这样就没法被domain用了，只能放到common里。但是放到common里，也只是解决了maven依赖不到的问题，app和domain还是直接依赖了技术细节

**Comment by wyyl1** [comment]
这个问题我是这么理解的：

**正常依赖关系**

domain 依赖 infrastructure：infrastructure 有什么接口，domain 就只能用什么接口

**依赖倒置**

infrastructure 依赖 domain：domain 要什么接口，infrastructure 就要实现什么接口

**推理**
common 如果在 infrastructure 中，但并不是 domain 主动提出需要使用的模块，如果 domain 使用了 common，则说明不是依赖倒置的关系，没有实现解藕

**参考**
《程序员的底层思维》作者：张建飞 ｜**10.2 依赖倒置解藕**
[我的笔记](https://www.wyyl1.com/post/20/3/#102-%E4%BE%9D%E8%B5%96%E5%80%92%E7%BD%AE%E8%A7%A3%E8%97%95)

**Comment by suikelei** [comment]
> 

我觉得是一回事。

依赖倒置是 具体实现层面的描述，让infrastructure 依赖 domain，domain只依赖自己定义的接口，避免了domain直接依赖infrastructure的具体实现，实现了解耦。

从功能实现的角度看，还是domain依赖infrastructure的能力。 而且在这个过程中，从domain的角度看，有可能是 我需要什么，要infrastructure来新实现这个功能，也有可能是infrastructure已经有了实现，domain要看下怎么抽象接口，把具体实现屏蔽了

**Comment by wyyl1** [comment]
我看[COLA 4.0：应用架构的最佳实践](https://blog.csdn.net/significantfrank/article/details/110934799)推荐做法是 Domain 与 Infrastructure 通过 Gateway 进行交互
Gateway 是防腐层

**Comment by suikelei** [comment]
> 我看[COLA 4.0：应用架构的最佳实践](https://blog.csdn.net/significantfrank/article/details/110934799)推荐做法是 Domain 与 Infrastructure 通过 Gateway 进行交互 Gateway 是防腐层

是的，这没问题，我的问题是。有可能出现当 domain想要用Infrastructure的某个能力，没有办法，或者不合适 抽象出接口来，让Infrastructure实现。
举例来说就是如果工具类放到了 Infrastructure，而 domain想要用这个工具类的话，只能是定义接口，让Infrastructure实现接口，将静态工具类包装成一个springbean出来给domian用，这个就不合适了

**Comment by yetao93** [comment]
1. 工具类应该放到COLA组件里
2. 对于diamond、switch等配置类，应该也是domain层抽象出接口，infrastructure实现

**Comment by significantfrank** [comment]
楼上说的不错。补充一点，使用依赖倒置，关键是要把需要防腐，需要转义的东西挡在外面。其它情况可以酌情妥协（自己拿捏），严格来说Spring、SLF4J也是技术细节，Domain层也在依赖不是。

**Comment by sparks345** [comment]
DDD 分层架构说 DB 操作，工具，Common 都比较稳定，所以理应放在最底层。
但是整洁架构、洋葱架构、六边形架构都说 Domain 应该是最核心的，只能被依赖。
然后就有了后面演化出的两种解决方案：
1. Infrastructure 放在最顶层
2. Domain 和 Infrastructure 依赖倒置

两种架构理念都很好，但是他们关注的侧重点不同，整合起来有点拧巴，个人觉得核心的原因还是 Infrastructure 的定义比较模糊。
* 如果是指纯粹的工具类，不涉及数据的流转，其实不应该架构分层需要统筹的范围内。
* 如果是指DB、网关、消息队列、外部服务这些基础数据的来源，那放在最外层（最顶层）然后 依赖倒置，让 Application 层 去协调也合理。

**Comment by zhangyanglei** [comment]
我见过另一种方式 domain依赖infra 将底层的db操作放到adapter层 分为driven跟driving
