### ISSUE TITLE
@PreInterceptor

### ISSUE THREAD

**Issue by Abnerring** [alibaba/COLA#37]
@PreInterceptor(commands = {cmd.class, cmd.class})？？？？
自定义无法调用？？？？

**Comment by nanshens** [comment]
目前不能针对cmd来加自定义post/preintercrptor, 只有全局生效的post/preintercrptor, 我自己改了一下代码， 可以实现你说的功能，不过没pr，我自用来着.

**Comment by colinger** [comment]
preintercrptor貌似不能保证在cmd初始化完成之前初始化吧？(demo)

**Comment by Abnerring** [comment]
> preintercrptor貌似不能保证在cmd初始化完成之前初始化吧？(demo)

不能

**Comment by significantfrank** [comment]
Interceptor has been deprecated
