### ISSUE TITLE
用了cola后我都不会写代码了

### ISSUE THREAD

**Issue by alansun2** [alibaba/COLA#377]
可能是还没理解，可能是还没习惯，用了cola 之后我都不会写代码了。以下是我的疑惑：
1. mybatis 中的方法是否需要做防腐通过gateway来调用？
2. Execute 类中涉及调用其他领域是通过其他领域的service 还是领域层调用？
3. 枚举类如果在client 层和基础层都有引用需要建两个吗？

**Comment by alansun2** [comment]
@lzy-git 那就说都要通过 service 层吗？那这样就会暴露到 api 层

**Comment by miaomiaocv** [comment]
> @lzy-git 那就说都要通过 service 层吗？那这样就会暴露到 api 层

个人理解是通过service去整合，用反腐层（gatewayImpl）去包装其他领域方法

**Comment by yetao93** [comment]
3. 枚举类不应该出现在client层吧
