### ISSUE TITLE
阿里官网不支持自动生成cola项目了吗

### ISSUE THREAD

**Issue by tongma89** [alibaba/COLA#378]
这个地址不自动生成cola项目了吗？ https://start.aliyun.com/bootstrap.html

**Comment by miyazawatomoka** [comment]
+1

**Comment by tongma89** [comment]
您的邮件我已收到,谢谢!

**Comment by daluotian** [comment]
> 您的邮件我已收到,谢谢!

是已经不支持了么？

**Comment by tongma89** [comment]
您的邮件我已收到,谢谢!

**Comment by significantfrank** [comment]
应该是不支持了，直接用Archetype生成也很方便

**Comment by tongma89** [comment]
您的邮件我已收到,谢谢!

**Comment by oldratlee** [comment]
已有的 Issue及其解答：

> - https://github.com/alibaba/COLA/issues/378#issuecomment-1408134662
>   > 应该是不支持了，直接用Archetype生成也很方便 by **`COLA` author** @significantfrank
> - https://github.com/alibaba/COLA/issues/354#issuecomment-1303032197
>   > 阿里云那个过时了，直接用archetype生成 by **`COLA` author** @significantfrank
> - https://github.com/alibaba/COLA/issues/196#issuecomment-872061727
>   > 阿里云的有些滞后，正确的做法是先按照领域分 by **`COLA` author** @significantfrank
> - https://github.com/alibaba/COLA/issues/283#issuecomment-1110817558
>   > 找阿里云的同学更新吧  by **`COLA` author** @significantfrank

**Comment by tongma89** [comment]
您的邮件我已收到,谢谢!
