### ISSUE TITLE
ReadMe和博客的图片有出入

### ISSUE THREAD

**Issue by rootwhois** [alibaba/COLA#385]
在ReadMe.md中，Scheduler位于Adapter层，但在[CSDN](https://blog.csdn.net/significantfrank/article/details/110934799)中，Scheduler位于App层。这里有点乱。

**Comment by rootwhois** [comment]
[csdn中的图片](https://img-blog.csdnimg.cn/img_convert/2450ba6358e9e68cb5b91f50ef3a7b0b.png)
[readme中的图片](https://camo.githubusercontent.com/7794e7335aa77e2a271b7989c8eb24cd5c5f3cd8efa77aebd71b858524051573/68747470733a2f2f696d672d626c6f672e6373646e696d672e636e2f36353439323330633637323334343866623361623531636137343832396538302e706e67)

**Comment by significantfrank** [comment]
以Readme为准，博客中有滞后
