### ISSUE TITLE
请问消息消费者和定时任务应该写到哪一层

### ISSUE THREAD

**Issue by ssPisces** [alibaba/COLA#388]
![image](https://user-images.githubusercontent.com/17402666/212026694-2a764cdc-aa56-43a3-8780-069651e3afa7.png)
![image](https://user-images.githubusercontent.com/17402666/212026861-abba3878-dae5-43b5-ad58-e49632177466.png)
已哪个为准
感谢！

**Comment by rootwhois** [comment]
#385 参考@significantfrank 给出的答复是，以ReadMe中的为准，所以应该是Adapter层。
