### ISSUE TITLE
在阿里云脚手架【分层应用】已经没有 cola了 ,这是啥原因呢

### ISSUE THREAD

**Issue by mrxlh** [alibaba/COLA#396]
https://start.aliyun.com/bootstrap.html

**Comment by Ryoui** [comment]
因为关系慢吧，经常这边4.0了，阿里云脚手架还在3.0。而且cola自己也提供命令，没必要整合到脚手架了

**Comment by tixo** [comment]
> 因为关系慢吧，经常这边4.0了，阿里云脚手架还在3.0。而且cola自己也提供命令，没必要整合到脚手架了

并不是慢，因为之前是有的，而现在没了。 COLA应该还是太麻烦了，用的少，慢慢就去掉了。

**Comment by oldratlee** [comment]
已有的 Issue及其解答：@scguoi 

> - https://github.com/alibaba/COLA/issues/378#issuecomment-1408134662
>   > 应该是不支持了，直接用Archetype生成也很方便 by **`COLA` author** @significantfrank
> - https://github.com/alibaba/COLA/issues/354#issuecomment-1303032197
>   > 阿里云那个过时了，直接用archetype生成 by **`COLA` author** @significantfrank
> - https://github.com/alibaba/COLA/issues/196#issuecomment-872061727
>   > 阿里云的有些滞后，正确的做法是先按照领域分 by **`COLA` author** @significantfrank
> - https://github.com/alibaba/COLA/issues/283#issuecomment-1110817558
>   > 找阿里云的同学更新吧  by **`COLA` author** @significantfrank
