### ISSUE TITLE
4.3.1中使用脚手架生成cola工程后，出现Could not find artifact com.alibaba.cola:cola-dummy-aggregation-parent:pom:dummy-SNAPSHOT

### ISSUE THREAD

**Issue by telepath1st** [alibaba/COLA#399]
![image](https://user-images.githubusercontent.com/12906522/225043022-3ff14602-d8c7-4402-b1a5-bfb52c47c263.png)

**Comment by oldratlee** [comment]
@telepath1st `cola-dummy-aggregation-parent`是`COLA`自己开发用的，不是这样的使用方式。

`COLA`具体的使用方式参见项目文档。
