### ISSUE TITLE
减少重复建设的建议和看法

### ISSUE THREAD

**Issue by mercyblitz** [alibaba/COLA#4]
本框架高度依赖 Spring Framework 4.3+ 和 Spring Boot 1.4+ ，建议直接使用底层实现，比如：
* `ValidatorI`  -> `org.springframework.validation.Validator`
* `ConvertorI`  -> `org.springframework.core.convert.converter.Converter` 或者 `org.springframework.core.convert.converter.GenericConverter`
* `ErrorCodeI` -> `org.springframework.validation.Errors`

以上只是举例部分内容，我的看法是应该重心放在核心的特性上。

**Comment by significantfrank** [comment]
挺不错的
