### ISSUE TITLE
异常处理，以及服务互相调用问题

### ISSUE THREAD

**Issue by ykkingzer** [alibaba/COLA#40]
1、CommandInvocation直接处理了异常，这里为什么不抛出异常，让controller层再统一处理呢？

**Comment by significantfrank** [comment]
controller是可选module，在RPC的环境下，不需要controller进行服务透出

**Comment by benxincaomu** [comment]
CommandInvocation不活了异常之后，如何保证事务呢，是否只能在Excutor这一层加事务控制呢？在复杂的业务场景，在保证事务的前提下使excutor用用复用的可能？
