### ISSUE TITLE
云原生应用脚手架里面怎么没有COLA了

### ISSUE THREAD

**Issue by scguoi** [alibaba/COLA#410]
https://start.aliyun.com/
看到一些介绍资料，是不是应该支持生成COLA项目的。怎么没有了，能解释下原因么？

**Comment by scguoi** [comment]
这是网上看到的一个截图。我关注这个是想知道，cloa是不是不推荐使用了？
![image](https://user-images.githubusercontent.com/19951594/230522505-f1e3a02a-e0d6-406f-815e-76ac7bdde2bf.png)

**Comment by oldratlee** [comment]
Duplicate.


-----

已有类似的Issue及其解答：  @scguoi 

- https://github.com/alibaba/COLA/issues/378#issuecomment-1408134662
  > 应该是不支持了，直接用Archetype生成也很方便 by `COLA` author @significantfrank
- https://github.com/alibaba/COLA/issues/354#issuecomment-1303032197
  > 阿里云那个过时了，直接用archetype生成 by `COLA` author @significantfrank
- https://github.com/alibaba/COLA/issues/283#issuecomment-1110817558
  > 找阿里云的同学更新吧  by `COLA` author @significantfrank
- https://github.com/alibaba/COLA/issues/196#issuecomment-872061727
  > 阿里云的有些滞后，正确的做法是先按照领域分 by `COLA` author @significantfrank
- #396
