### ISSUE TITLE
不太理解service层和domain层的差异

### ISSUE THREAD

**Issue by cwt9562** [alibaba/COLA#427]
可能我比较老旧，我的程序一般是Controller+Service+Dao(mybatis的mapper)+POJO
我阅读了cola的架构，我感觉将Service拆成了service和domain两层，dao演变成infra层
想了解下，一个功能，放service还是domain，有严格的限定么？

**Comment by witskeeper** [comment]
我觉得service层是多余的，controller层直接调用cmdexe就行

**Comment by HengCC** [comment]
它这个是DDD的思想. 但是实际应用中. 很难贯彻这个思想. domain存在的核心意义是内聚共性业务. 降低和其他模块的耦合. 你所说的service更多的职责是利用多个domain或者infra服务对外提供数据的这一层,因此大部分场景里面. 如果你们不在搞DDD. 我觉得domain是可以忽略掉的. 只管app和infra层即可.
