### ISSUE TITLE
提问有应用cola的比较有名一点的开源项目吗？

### ISSUE THREAD

**Issue by KANLON** [alibaba/COLA#439]
提问有应用cola的比较有名一点的开源项目吗？目前找不到一个比较成熟的应用cola的项目来参考，官方可以列个使用了cola的项目出来吗？

**Comment by zq99299** [comment]
同问，官网这个了解还是比较少，如果有相关系统在应用，可以作为一些参考

**Comment by zq99299** [comment]
今天根据官网文档生成了一个骨架项目，研究了下，骨架项目里面的调用链不完整，文档上很多概念无法得到佐证，大部分概念都无法理解，希望有一个小型的功能模块项目，能演示下到底该如何实施落地

**Comment by KouShenhai** [comment]
KCloud-Platform-Alibaba（老寇云平台）是一个企业级微服务架构的云服务平台。基于Spring Boot 3.1.4、Spring Cloud 2022.0.4、Spring Cloud Alibaba 2022.0.0.0 最新版本开发的多租户SaaS系统。 遵循SpringBoot编程思想，使用阿里COLA应用框架构建，高度模块化和可配置化。具备服务注册&发现、配置中心、服务限流、熔断降级、监控报警、多数据源、工作流、高亮搜索、定时任务、分布式链路、分布式缓存、分布式事务、分布式存储等功能，用于快速构建微服务项目。目前支持Shell、Docker等多种部署方式，实现RBAC权限、其中包含系统管理、系统监控、工作流程、数据分析等几大模块。 遵循阿里代码规范，采用RESTful设计风格，代码简洁、架构清晰，非常适合作为基础框架使用。

**Comment by significantfrank** [comment]
COLA是一个设计理念，阿里、华为、京东、招商银行的很多应用都在使用
