### ISSUE TITLE
EventBus使用问题

### ISSUE THREAD

**Issue by capqueen** [alibaba/COLA#44]
demo里的DomainEventPublisher，实现的publish调用的是 eventBus的fire方法。我看了源代码，fire只执行了第一个handler。然后另外提供了一个fireAll和asyncFire。
我想问的是
1. 我有多个handler 是不是要自己实现一个frieall的publisher。
2.既有异步又有同步的话，是不是要既要调用fireall 又要调用asyncfire

**Comment by significantfrank** [comment]
是这样的
