### ISSUE TITLE
Client 这个包同时被domain，和app依赖，但是client的实现是app 这个看着有点费解？请帮忙解惑

### ISSUE THREAD

**Issue by jiangyiman** [alibaba/COLA#441]

**Comment by zq99299** [comment]
个人觉得这个只适合使用 dubbo 这样的 rpc 框架，对于 Feign 这样的方式，就不合适

**Comment by hnsongbiao** [comment]
> 从官方的文档是这样解释的：服务对外透出的api，既然是api那么和app的关系就不用解释了，是app应用对外的服务公开，这点注意和adapter是有区别的，适配面向的是客户端应用，而client面向的是其它服务，关于domain，并没有直接依赖的，就算领域服务中需要加载其它服务的数据其实用的是gateway做控制反转，然后在gateway的接口实现中进行调用其它服务的api

这里"就算领域服务中需要加载其它服务的数据其实用的是gateway做控制反转，然后在gateway的接口实现中进行调用其它服务的api",是意思应用的别人的client

**Comment by hnsongbiao** [comment]
![image](https://github.com/alibaba/COLA/assets/10285955/35604daf-c961-46ed-82fc-a402a22fa132)

从架构图上看，domain并没有引用client

**Comment by AmbitionLover** [comment]
domain 只关心本领域，不应用外部， 如外部 在app 中进行功能编排了~
个人愚见

**Comment by significantfrank** [comment]
domain不依赖client，client也是可选的
