### ISSUE TITLE
关于COLA的使用问题

### ISSUE THREAD

**Issue by shubiaodian** [alibaba/COLA#449]
mvn archetype:generate \
    -DgroupId=com.alibaba.cola.demo.web \
    -DartifactId=demo-web \
    -Dversion=1.0.0-SNAPSHOT \
    -Dpackage=com.alibaba.demo \
    -DarchetypeArtifactId=cola-framework-archetype-web \
    -DarchetypeGroupId=com.alibaba.cola \
    -DarchetypeVersion=4.3.2

命令执行大概需要多久啊？为什么我执行了十几分钟还没有执行完毕？

**Comment by shubiaodian** [comment]
原来是需要确认信息啊

**Comment by JackJiang1234** [comment]
unsubscribe



在 2023-09-05 19:54:28，"shubiaodian" ***@***.***> 写道：

原来是需要确认信息啊
