### ISSUE TITLE
依赖缺失问题

### ISSUE THREAD

**Issue by keejo125** [alibaba/COLA#45]
使用命令创建demo，或者直接对samle进行mvn install 都报错，是maven中心库缺少包了么？
麻烦帮忙看看，谢谢

`[INFO] craftsman.all ...................................... SUCCESS [  0.213 s]
[INFO] craftsman-client ................................... FAILURE [  2.795 s]
[INFO] craftsman-infrastructure ........................... SKIPPED
[INFO] craftsman-domain ................................... SKIPPED
[INFO] craftsman-app ...................................... SKIPPED
[INFO] craftsman-controller ............................... SKIPPED
[INFO] start .............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.349 s
[INFO] Finished at: 2019-12-05T09:28:13+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project craftsman-client: Could not resolve dependencies for project com.alibaba.craftsman:craftsman-client:jar:1.0.0-SNAPSHOT: Could not find artifact com.alibaba.cola:cola-common:jar:2.0.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project craftsman-client: Could not resolve dependencies for project com.alibaba.craftsman:craftsman-client:jar:1.0.0-SNAPSHOT: Could not find artifact com.alibaba.cola:cola-common:jar:2.0.0 in central (https://repo.maven.apache.org/maven2)
`

**Comment by jackyfan** [comment]
自己拉代码mvn install

**Comment by significantfrank** [comment]
是的 没有上传到中心库
