### ISSUE TITLE
各位老师，请问使用cola-archetype-web生成的工程和介绍的有些不一样

### ISSUE THREAD

**Issue by Creating-ZXY** [alibaba/COLA#455]
使用cola-archetype-web生成的web工程里面也有一些类文件，和简介里面介绍的路径、名称的定义都不太一致，甚至生成的一个mapper.xml文件路径还是错的。
包括生成的web工程和cola-samples下给的craftsman具体的结构也不太一致。让我这种菜鸟看起来听困惑的，不知道以哪个为准？不知道作者，有计划重新梳理一下代码吗？

另外，各位老师，有推荐的COLA demo可以学习吗？或者DDD demo工程学习学习。

**Comment by bvans** [comment]
笑死，我也试了一下，果然是错的，面试kpi的开源吧
