### ISSUE TITLE
locateComponent获取不到循环对象。

### ISSUE THREAD

**Issue by jackyfan** [alibaba/COLA#46]
BizScenario.getUniqueIdentity方法useCase、scenario为空则使用默认值，这样子doRegistration方法调用BizScenario.getUniqueIdentity，useCase、scenario为空返回是xxx.defaultUseCase.defaultScenario。而ExtensionExecutor.loopTry方法在解析bizScenario时对useCase、scenario进行截取，并不会补充useCase、scenario的默认值，这样导致locateComponent找不到对应的扩展类。

**Comment by acpipe** [comment]
#51  可以看下merge request
