### ISSUE TITLE
微信业务之类的第三方介入组件应该放在哪一层

### ISSUE THREAD

**Issue by originyy** [alibaba/COLA#477]
微信业务之类的第三方介入组件应该放在哪一层呢？

如果有相关的很多的业务，感觉可以独立成一个服务，但这是另外的话题。

如果是在同一个服务里，感觉有两个选择：
1.较为简单的可以封装成一个组件，这时候放client层还是放app层，感觉client层是用来对外暴露的？会不会对外暴露太多不必要的细节

2.相对业务比较复杂的考虑定义为一个领域，这时候放app层还是放domain层呢?我感觉好像是可以放domain的，但是他需要调用外部的东西。

还不是非常理解，求细说

**Comment by readilychen** [comment]
个人理解是在gateway里抽象，放到infra里impl。

**Comment by mike1024-hub** [comment]
我理解的是，第三方业务一定是与app和domain无关的。第三方是输入数据就放在adapter层，调用或者输出数据就放在infra，接口在domain中，但domain的接口一定不要有第三方业务侵染。
