### ISSUE TITLE
循环依赖

### ISSUE THREAD

**Issue by PerfecterDay** [alibaba/COLA#482]
为了隔离接口与实现，通常会在domain 层抽象设计领域层需要的外部服务接口，然后在 infrastructure 层做具体实现。这样就要求 infrastructure 层会依赖domain层（单纯的pom 依赖而非DDD概念上）。这样就有循环依赖问题了。能否在 domain 包（层）中单独抽离一个 pom module 以让 infrastructure 依赖。

**Comment by significantfrank** [comment]
domain不依赖任何其它层次，何来的循环
