### ISSUE TITLE
聚合型Domain Entity应该如何处理持久化？

### ISSUE THREAD

**Issue by uliian** [alibaba/COLA#484]
我有一个AEntity，里面包含了BEntity。持久化读写时，是通过AGateway依赖BGateway去一体化读写组装AEntity合适还是通过APP层依赖AGateway和BGateway在APP层组装成AEntity更加合理？

**Comment by mike1024-hub** [comment]
聚合是一个整体，不能跨越聚合持久化

**Comment by significantfrank** [comment]
在App层做持久化的事情，尽量不要让Entity做持久化的事情
