### ISSUE TITLE
app 层的service 里面的方法返回对象为什么是包装类Response 而不是原始的对象

### ISSUE THREAD

**Issue by fengdh23** [alibaba/COLA#494]
public interface MetricsServiceI {
    Response addATAMetric(ATAMetricAddCmd cmd);
    Response addSharingMetric(SharingMetricAddCmd cmd);
    MultiResponse<ATAMetricCO> listATAMetrics(ATAMetricQry ataMetricQry);
}

是不是原始的对象更直观、好理解

**Comment by youngledo** [comment]
确实，感觉作者对不同层级的实体处理不怎么样

**Comment by significantfrank** [comment]
封装是为了统一格式，isSuccess, errorMessage
