### ISSUE TITLE
Domain 层的出入参要 domain 层自己维护的话不会爆炸多吗？还是都用 entity？总不能引用 client 包下的吧

### ISSUE THREAD

**Issue by felix9ia** [alibaba/COLA#552]
前提： 作者说 domain 领域是应用的核心，不依赖任何其他层次

我的疑惑是，为了保持domain层的独立性，在 domain 层，入参该不该新建 DTO 来支持？

比如创建店铺  shopGateway.createShop(Shop newShop)

方案1： 如果 newShop 直接用 entity ，但新建店铺又不需要 shopNo、ctime、utime 等字段。

方案2： 难道在给 domain 包下新增一个 DTO 包，里面放着 DTO 或者 Command 或者 query ？这个数量又是爆炸的多

方案3：总不能去引用 client 包的 Command 和 query 吧。client 本身是给 SDK 用的，有些不暴露给 client 的接口反而把不暴露接口的入参都定在了client 层，显然不合理。

方案4：入参都用字段做参数，比如(String shopName, String shopDesc)，这明显不具备重构时的扩展性。

我现在打算都用 entity 做入参。因为我看了官方的 craftsman 的 gateway，入参要么都是用字段做参数，要么就是引用了 entity。

而且其他方案明显有缺陷....难道这就是代价？

BTW，COLA 在 App 层 实践的 CQRS 的收益到底在哪里？我用 xxQueryService 和 xxCommandService 是不是也能实现读和写的隔离...

**Comment by felix9ia** [comment]
新建一个 common 包，来放置 这些 cmd 和 query 应该是合适的，总不能让这些 cmd 和 query 都止步于 app 层吧。

就不知道符不符合 domain 领域不依赖任何层次的要求

**Comment by felix9ia** [comment]
cmd 和 query 还是不能跨过 domain 入侵到 gateway 上，
原因 1：这样在 app 层做完的 cmd 和 query 的 Assembler，又得在 gataway 的 impl 里重新做一遍，
原因2： 而且在 domain 上做完的类似状态转化的动作， gateway 就感知不到了，相当于 gateway  成了 app 层的奸细， 把  domain 架空了.....

看来 domain 层智能选择我上面的方案1，所有gateway 上的入参都得用 entity

**Comment by felix9ia** [comment]
要想不浪费 cmd 和 query 这些参数，感觉需要用 domainservice 把 app层和 gateway 层彻底隔离起来，让 domainservice 来承接 cmd 和 query ，

但是，这样 domainservice  又把 app 层的 service 架空了，而且 domainservice 的角色似乎也不应该干这事儿....

所以 cmd 和 query 只能止步于 app 层....

**Comment by felix9ia** [comment]
我应该是找到一个比较合适的方案，这样也调用的 domain 的积极性。

拿更新店铺位置的动作来说。

在 App 层,分成三个步骤，查询店铺、更新位置，保存，重点是更新位置要放在 entity 里，  setLocation(ShopLocationCmd shopLocationCmd, Long userId)  。

```
    public Response updateShopInfoLocation(ShopLocationCmd shopLocationCmd) {
        Long userId = UserContext.currentUserId(true);

        Shop existShop = checkExistShop(shopLocationCmd.getShopNo());
        existShop.setLocation(shopLocationCmd, userId);
        shopGateway.updateShop(existShop, userId);
        return Response.buildSuccess();
    }
```
在 entity 中,把 ShopLocationCmd 作为入参
```
    public void setLocation(ShopLocationCmd shopLocationCmd, Long userId) {
        Shop currentShop = shopGateway.getByShopNo(shopLocationCmd.getShopNo(), false);
        if (currentShop == null) {
            throw new BizException(ErrorCode.B_SHOP_shopNotFound.getErrCode(), ErrorCode.B_SHOP_shopNotFound.getErrDesc());
        }
        this.setShopAddressDesc(shopLocationCmd.getShopAddressDesc());
        this.setShopLatitude(shopLocationCmd.getShopLatitude());
        this.setShopLongitude(shopLocationCmd.getShopLongitude());
        this.setShopStatusCode(ShopStatus.ACTIVE.getCode().longValue());
        shopGateway.updateShop(this, userId);
    }
```

这样子，domain 层充分利用了 cmd，也不会导致可读性降低，可能让其他开发者误以为更新操作会涉及到其他不相关的字段，增加了代码审阅的复杂性。

：）

**Comment by felix9ia** [comment]
我发现，让 domain 依赖 client 包还是不合适

但我的困惑是脚手架初始化项目时，domain 就依赖了 client 包，既然添加了依赖，总有依赖的根据吧？

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.unrealdie.stall</groupId>
        <artifactId>stall-api-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>stall-api-domain</artifactId>
    <packaging>jar</packaging>
    <name>stall-api-domain</name>

    <dependencies>
        <dependency>
            <groupId>com.unrealdie.stall</groupId>
            <artifactId>stall-api-client</artifactId>
        </dependency>

        <!-- COLA components -->
        <dependency>
            <groupId>com.alibaba.cola</groupId>
            <artifactId>cola-component-domain-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cola</groupId>
            <artifactId>cola-component-exception</artifactId>
        </dependency>
        <!-- COLA components End-->
    </dependencies>
</project>
```

**Comment by felix9ia** [comment]
https://github.com/alibaba/COLA/issues/557

**Comment by franciszhang** [comment]
> #557

哥们，你们公司有在用这框架吗

**Comment by felix9ia** [comment]
> > #557
> 
> 哥们，你们公司有在用这框架吗

是的，在用，目前用起来感觉不错

**Comment by frank8g2g3** [comment]
> > > #557
> > 
> > 
> > 哥们，你们公司有在用这框架吗
> 
> 是的，在用，目前用起来感觉不错

能否把项目分享出来，学习参考一下

**Comment by felix9ia** [comment]
> 不要那么死板，在实践中还是要根据场景来看 https://developer.aliyun.com/article/715802 可看一下这遍文章，在大部分场景下抽一个types出来会更适合，就是你提到的common模块，用来放置全局依赖的类型，如枚举、公共类型

@remind 感谢分享，很受用。但是我现在有新的问题想请教：
我是不是直接让Domain 模块直接依赖 Client 模块就可以了？
因为：types/Common 模块和 Client 模块的角色有点冲突...就是什么样的POJO 放到 Common ，什么样的 POJO 适合放到 Client？

一个问题场景：

- 当 Gateway 用于承接其他 RPC 服务，定义出入参的时候（不考虑需要修剪DTO的情况），我该依赖 Client 模块还是 Common 模块？

比如，订单服务需要调用支付服务，那就需要在订单服务新建一个 transactionGatway 来对接支付服务的 transactionAppService，这些出入参DTO(Cmd,Query,CO)我应该放在 Client 模块还是 Common 模块？

同理，同一个服务下调用， Gateway 的 出入参DTO(Cmd,Query,CO) 应该怎么放置合适，来提高复用性？

**Comment by remind** [comment]
> Client

你说的场景是放到common模块
client和common的分工分别为：

1. client是定义对外要提供的接口，所以里面主要就只是接口定义，其中所依赖的pojo应该是都放到common模块，所以client是依赖common的。
2. common是定义需要对外提供同时内部也需要使用的对象，一般是值对象，所以common是被client和domain所依赖。

如果你不做拆分，全部放到client中，然后domain依赖client，效果确实是一样的，但为什么不提倡这样做，是因为client定义的接口对于domain是没有任何作用的，如果domain中有人去使用了client的接口，反而造成循环调用。
