### ISSUE TITLE
 Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate (default-cli) on project standalone-pom: The desired archetype does not exist (com.alibaba.cola:cola-framework-archetype-web:2.0.0) -> [Help 1]

### ISSUE THREAD

**Issue by hunshikan** [alibaba/COLA#56]

**Comment by yeongjet** [comment]
same problem

**Comment by yeongjet** [comment]
@hunshikan windows命令行下含有英文句号`.`的地方要加上引号: 
`mvn archetype:generate  -DgroupId="com.alibaba.demo" -DartifactId=demo -Dversion="1.0.0-SNAPSHOT" -Dpackage="com.alibaba.demo" -DarchetypeArtifactId=cola-framework-archetype-web -DarchetypeGroupId="com.alibaba.cola" -DarchetypeVersion="2.0.0"`
建议作者注明下。

**Comment by yeongjet** [comment]
.idea这个文件夹也带进来了..
