### ISSUE TITLE
一个service方法对应一个命令，如果业务复杂会不会导致command类过多呢？

### ISSUE THREAD

**Issue by hunshikan** [alibaba/COLA#57]

**Comment by qq240996777** [comment]
业务复杂就是需要多个类来解决编排问题，难道想要万能类吗？
复杂的问题都是可以分拆成若干个小问题来解决的。

**Comment by peng2035** [comment]
> 业务复杂就是需要多个类来解决编排问题，难道想要万能类吗？
> 复杂的问题都是可以分拆成若干个小问题来解决的。

话不是那么说的啊，如果java设计只有class 没有method你是什么想法。。。

**Comment by peng2035** [comment]
> 业务复杂就是需要多个类来解决编排问题，难道想要万能类吗？
> 复杂的问题都是可以分拆成若干个小问题来解决的。

完全可以通过方法级别加command注解或者其他方式来解决，非要建那么多类，项目显得特别臃肿

**Comment by hellereye** [comment]
1. service不是技术上的service层，service可以分为Application service、Domain Services和Infrastructure Services，可以参考这篇
https://stackoverflow.com/questions/2268699/domain-driven-design-domain-service-application-service?rq=1
2。Cola中有“业务线”（bizcode）、场景（usecase）和阶段（phase）的概念，这些概念聚合command满足业务需求；command多少与否是由业务场景决定的。
个人理解

**Comment by dilantaya** [comment]
感觉例子很少啊 “业务线”（bizcode）、场景（usecase）和阶段（phase）在代码里怎么体现

**Comment by hellereye** [comment]
@dilantaya “业务线”（bizcode）、场景（usecase）和阶段（phase）在COLA中的扩展坐标中有所体现，但在框架中没有具体编程对象；主要说明的是COmmand和service没有一一对应的关系

**Comment by significantfrank** [comment]
合理的顾虑，在cola3.0中去掉了command概念，把选择权交还给开发者
