### ISSUE TITLE
[疑问] 为什么客户端对象使用 CO 而不是 VO？

### ISSUE THREAD

**Issue by fxleyu** [alibaba/COLA#59]
例如 `com.alibaba.craftsman.dto.clientobject.ATAMetricCO` ，而不是使用 VO 结尾？

正常情况下，VO 不是更加通用吗？

**Comment by xiaogangfan** [comment]
> 例如 `com.alibaba.craftsman.dto.clientobject.ATAMetricCO` ，而不是使用 VO 结尾？
> 
> 正常情况下，VO 不是更加通用吗？

我理解VO 指的是View Object，更能强调面向前端，二CO面向的是客户端（前后端各种）

**Comment by fxleyu** [comment]
> > 例如 `com.alibaba.craftsman.dto.clientobject.ATAMetricCO` ，而不是使用 VO 结尾？
> > 正常情况下，VO 不是更加通用吗？
> 
> 我理解VO 指的是View Object，更能强调面向前端，二CO面向的是客户端（前后端各种）

THX

**Comment by significantfrank** [comment]
是这样的

**Comment by tuozixuan** [comment]
为什么ClientObject没有继承DTO？
