### ISSUE TITLE
为啥引进不了com.alibaba.cola依赖呢

### ISSUE THREAD

**Issue by jiangsiYang** [alibaba/COLA#63]
<dependency>
                <groupId>com.alibaba.cola</groupId>
                <artifactId>cola-common</artifactId>
                <version>2.0.0</version>
            </dependency>

**Comment by Xmagic** [comment]
You need git clone the cola-framework and maven install it to your local repository first.

**Comment by fengshanbieyuan** [comment]
能不能在公共库发布下相关依赖啊，在项目里不太好用啊，如果没有私有的 repo，还得每个开发都要 install 到本地。。。。

**Comment by significantfrank** [comment]
You can also get it from central repository：https://oss.sonatype.org/#nexus-search;quick~cola-core
