### ISSUE TITLE
Hardcoded file separator

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [alibaba/COLA#65]
https://github.com/alibaba/COLA/blob/bc57c0f8e7383d2981a9fafe761eea987ff21c39/cola-framework/cola-test/src/main/java/com/alibaba/cola/mock/utils/FileUtils.java#L49

The path split symbol problem is different for different operating systems. Hard-coded file separators should not be used. Instead, use a platform-independent API provided by the language library,such as java.io.File.separator or java.lang.System.getProperty("file.separator")

**Comment by significantfrank** [comment]
removed
