### ISSUE TITLE
sample中的测试类跑不起来，怎么解决呢？

### ISSUE THREAD

**Issue by lkun** [alibaba/COLA#68]
初步怀疑是否 spring-mock-test.xml 配置无法加载进去导致无法排除Mapper？
![企业微信截图_20200206122226](https://user-images.githubusercontent.com/2719052/73905792-7d925080-48db-11ea-82b4-a7e02be0cfab.png)
![企业微信截图_20200206122414](https://user-images.githubusercontent.com/2719052/73905823-97cc2e80-48db-11ea-8027-e6994481e489.png)

**Comment by significantfrank** [comment]
这个是使用Mock工具，现在去除了，看最新的sample
