### ISSUE TITLE
关于依赖倒置的domain单元测试问题

### ISSUE THREAD

**Issue by neo2008cat** [alibaba/COLA#70]
想问下，对于DIP，infrastruture依赖domain(实际上是domain的gateway)，而实际运行中domain是依赖infrastruture的执行的。在domain单元测试中，因为并没有mock gateway实现，会发现除非引入infrastruture，否则是跑不起来的；但是引入infrastruture又导致了与domain的循环依赖问题。请问是如何解决的？ 是否要把gateway独立出模块？

**Comment by significantfrank** [comment]
单测是需要mock的，domain+Infrastructure都要测的话，就是继承测试了
