### ISSUE TITLE
状态机获取 PlantUML 字符串或流程图

### ISSUE THREAD

**Issue by dudiao** [alibaba/COLA#73]
大佬我又来了，请教个问题：

现在`StateMachine#generatePlantUML()`和`com.alibaba.cola.statemachine.Visitor`的返回值都是void，当想获取PlantUML字符串或流程图时，只能从控制台复制出来，然后再渲染。**能否设计出接口**，直接获取PlantUML字符串或流程图呢？官方给个默认实现或者自己实现都行。

如果可行，我可以试着提交PR

**Comment by significantfrank** [comment]
提交PR吧
