### ISSUE TITLE
CommandInvocation如何添加自定义的CommandInterceptor

### ISSUE THREAD

**Issue by aywangchen** [alibaba/COLA#75]
### **现象**
查看源码发现目前只是在CommandRegister中为CommandInvocation添加了全局的globalPreInterceptors和globalPostInterceptors。

### **问题**
需要给CommandInvocation添加自定义的CommandInterceptor项目中有合适的入口吗？

**Comment by significantfrank** [comment]
该功能已经在3.0中移除
