### ISSUE TITLE
事务如何实现呢？

### ISSUE THREAD

**Issue by wzq21st** [alibaba/COLA#8]
application层是系统用例模型的反映，拼装各种Domain层业务逻辑，事务应该配置在*CmdExe的方法上吧

**Comment by jackyfan** [comment]
从DDD的角度应该放到聚合根上domain层。

**Comment by smalldok** [comment]
从COLA作者文章来看，貌似是放在application层

**Comment by significantfrank** [comment]
事务属于技术细节，不在本框架scope内
