### ISSUE TITLE
sample的domain依赖了infrastructure和client，没有进行依赖反转,与应用架构图不符

### ISSUE THREAD

**Issue by hubertwng** [alibaba/COLA#83]
![image](https://user-images.githubusercontent.com/15893852/82785628-9415e500-9e95-11ea-9301-7661b988a5cb.png)
![image](https://user-images.githubusercontent.com/15893852/82785770-d808ea00-9e95-11ea-997f-628d2993edba.png)

**Comment by 123huangzhengang** [comment]
我也有这样的疑问，依赖倒置没法做了

**Comment by dilantaya** [comment]
感觉sample 他们没更新 还是1.0的

**Comment by hellereye** [comment]
同感；

**Comment by codering** [comment]
- 把源码clone下拉
- 把cola-archetype-service和cola-archetype-web通mvn install 安装到本地repository
- 通过命令来生成demo

这样就没问题。

**Comment by significantfrank** [comment]
不好意思，sample的确没有更新，我今天fix一下

**Comment by significantfrank** [comment]
已经调整过来了
![image](https://user-images.githubusercontent.com/8212932/86317737-c8ce4680-bc62-11ea-84c3-45a9ac6b65e8.png)
