### ISSUE TITLE
开源协议是LGPL，COLA在项目中怎么使用才不需要履行对应的开源要求？

### ISSUE THREAD

**Issue by xionghuan1984** [alibaba/COLA#85]
为什么不是更友好的其他协议?基于什么原因使用LGPL？

**Comment by significantfrank** [comment]
可以直接用

**Comment by kualer** [comment]
> 为什么不是更友好的其他协议?基于什么原因使用LGPL？

也是想不明白，这个商业最好不要使用。LGPL是作为第三方库LINK才在商业里引用的吧。
