### ISSUE TITLE
event事件触发异常会报空指针

### ISSUE THREAD

**Issue by kevinkeh** [alibaba/COLA#87]
代码类EventBus,eventHub.getResponseRepository()这个map没有put数据，导致获取会报空指针

` private Response handleException(EventHandlerI handler, Response response, Exception exception) {
        logger.error(exception.getMessage(), exception);
        Class responseClz = eventHub.getResponseRepository().get(handler.getClass());
        try {
            response = (Response) responseClz.newInstance();
        } catch (Exception e) {
            logger.error(e.getMessage(), e);
            throw new ColaException(e.getMessage());
        }
        if (exception instanceof BaseException) {
            ErrorCodeI errCode = ((BaseException) exception).getErrCode();
            response.setErrCode(errCode.getErrCode());
        }
        else {
            response.setErrCode(BasicErrorCode.SYS_ERROR.getErrCode());
        }
        response.setErrMessage(exception.getMessage());
        return response;
    }`

**Comment by kevinkeh** [comment]
@significantfrank

**Comment by significantfrank** [comment]
fixed

**Comment by JeryChen** [comment]
@significantfrank 
Hello, the current version of the source code, did not see the repair.
