### ISSUE TITLE
关于demo代码结构的2个问题

### ISSUE THREAD

**Issue by bz008** [alibaba/COLA#89]
1、Domain里面的Customer继承com.alibaba.demo.dto.domainmodel.Customer，dto跟entity一般不是一一对应的，dto为了满足业务需要可能组装了多个entity的属性，entity继承dto不适合
2、看CustomerGateway代码就是资源库接口，从它Gateway里面提出来名字直接叫CustomerRepository更好理解，这样更DDD。跟外部打交道的所有代码放在Gateway下不做区分会有点乱，像六边形架构区分不同类型端口看着更整洁

**Comment by significantfrank** [comment]
很好的问题，entity继承dto，不是一个很好的practice，我会改掉。关于端口是否要分类，通过名字区分，这个点还好，叫Gateway会更通用一点。
