### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by xiaosagehua** [alibaba/COLA#96]
Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate (default-cli) on project standalone-pom: The desired archetype does not exist (com.aliyun:cola-framework-archetype-web:3.0.0) -> [Help 1]

**Comment by xiaosagehua** [comment]
Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate (default-cli) on project standalone-pom: The desired archetype does not exist (com.aliyun:cola-framework-archetype-web:3.0.0) -> [Help 1]

**Comment by NaturalL** [comment]
看着是 archetypeGroupId 变了，要用com.alibaba.cola 

mvn archetype:generate  -DgroupId=com.alibaba.demo -DartifactId=demoService -Dversion=1.0.0-SNAPSHOT -Dpackage=com.alibaba.demo -DarchetypeArtifactId=cola-framework-archetype-service -DarchetypeGroupId=com.alibaba.cola -DarchetypeVersion=3.0.0

**Comment by gysheng** [comment]
我也是报这个错
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate (default-cli) on project standalone-pom: The desired archetype does not exist (com.aliyun:cola-framework-archetype-service:3.0.0) -> [Help 1]

**Comment by acenra** [comment]
缺少cola-test

**Comment by LinZhaoguan** [comment]
最新的**正确命令**：mvn archetype:generate  -DgroupId=com.alibaba.demo -DartifactId=demo -Dversion=1.0.0-SNAPSHOT -Dpackage=com.alibaba -DarchetypeArtifactId=cola-framework-archetype-web -DarchetypeGroupId=com.alibaba.cola -DarchetypeVersion=3.0.0

**Comment by yanxinquanboe** [comment]
**注意参数是这个 ：**    -DarchetypeGroupId=com.alibaba.cola

**Comment by StormSpiritZipZap** [comment]
C:\Users\Administrator>mvn archetype:generate -DgroupId=com.alibaba.demo -DartifactId=demo -Dversion=1.0.0-SNAPSHOT -Dpackage=com.alibaba -DarchetypeArtifactId=cola-framework-archetype-web -DarchetypeGroupId=com.alibaba.cola -DarchetypeVersion=3.0.0
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> maven-archetype-plugin:3.2.0:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO]
[INFO] <<< maven-archetype-plugin:3.2.0:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO]
[INFO] --- maven-archetype-plugin:3.2.0:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Interactive mode
[WARNING] No archetype found in remote catalog. Defaulting to internal catalog
[WARNING] Archetype not found in any catalog. Falling back to central repository.
[WARNING] Add a repository with id 'archetype' in your settings.xml if archetype's repository is elsewhere.
[WARNING] The POM for com.alibaba.cola:cola-framework-archetype-web:jar:3.0.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.251 s
[INFO] Finished at: 2020-08-04T17:52:48+08:00
[INFO] Final Memory: 19M/298M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.0:generate (default-cli) on project standalone-pom: The desired archetype does not exist (com.alibaba.cola:cola-framework-archetype-web:3.0.0) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by yanxinquanboe** [comment]
cd 到 cola-archetype-service
然后执行 mvn install安装到本地
如下作者的提示：
直接运行上面提供的Archetype命令就可以生成应用，如果你的Remote Maven Repository里面没有Archetype的Jar包，也可以自己下载Archetype到本地，然后本地运行 mvn install安装。

**Comment by raostu** [comment]
赞

**Comment by significantfrank** [comment]
这个archetype之前有些混乱，最近统一治理了下，也对cola进行了升级，现在已经上传到中央仓库，不需要本地install了，直接可以用，具体看readme

**Comment by derekzhan** [comment]
![image](https://user-images.githubusercontent.com/2375460/136948355-f6663a64-dc88-4e47-993b-b96ce88104c7.png)
我也遇到了同样的问题
