### ISSUE TITLE
README.md documentation content error

### ISSUE THREAD

**Issue by yaoyucheng** [alibaba/COLA#99]
original text：mvn archetype:generate  -DgroupId=com.alibaba.demo -DartifactId=demoService -Dversion=1.0.0-SNAPSHOT -Dpackage=com.alibaba.demo -DarchetypeArtifactId=cola-framework-archetype-service -DarchetypeGroupId=com.aliyun -DarchetypeVersion=3.0.0

Error：-DarchetypeGroupId=com.aliyun
Correct ： -DarchetypeGroupId=com.alibaba.cola

The same：mvn archetype:generate  -DgroupId=com.alibaba.demo -DartifactId=demoWeb -Dversion=1.0.0-SNAPSHOT -Dpackage=com.alibaba.demo -DarchetypeArtifactId=cola-framework-archetype-web -DarchetypeGroupId=com.aliyun -DarchetypeVersion=3.0.0

Error：-DarchetypeGroupId=com.aliyun
Correct ： -DarchetypeGroupId=com.alibaba.cola

**Comment by significantfrank** [comment]
updated
